/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50729
 Source Host           : 127.0.0.1:33060
 Source Schema         : dongsen

 Target Server Type    : MySQL
 Target Server Version : 50729
 File Encoding         : 65001

 Date: 28/04/2020 18:25:09
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for animal
-- ----------------------------
DROP TABLE IF EXISTS `animal`;
CREATE TABLE `animal` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `image` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `sex` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `character` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `race` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `birth` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `tag` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1192 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of animal
-- ----------------------------
BEGIN;
INSERT INTO `animal` VALUES (795, '../images/阳明.png', '阳明', '♂', '暴躁', '食蚁兽', '3月9日', '有的');
INSERT INTO `animal` VALUES (796, '../images/阿诚.png', '阿诚', '♂', '运动', '食蚁兽', '10月20日', '真诚');
INSERT INTO `animal` VALUES (797, '../images/贵妃.png', '贵妃', '♀', '成熟', '食蚁兽', '10月24日', '麻烦了');
INSERT INTO `animal` VALUES (798, '../images/丽婷.png', '丽婷', '♀', '元气', '鸟', '4月18日', '山雀');
INSERT INTO `animal` VALUES (799, '../images/恰咪.png', '恰咪', '♀', '元气、大姐姐', '大熊', '4月17日', '唷咻');
INSERT INTO `animal` VALUES (800, '../images/铁熊.png', '铁熊', '♂', '暴躁', '大熊', '7月1日', '嗯唔');
INSERT INTO `animal` VALUES (801, '../images/喳喳.png', '喳喳', '♀', '成熟', '鸟', '12月4日', '喳');
INSERT INTO `animal` VALUES (802, '../images/妮雅.png', '妮雅', '♀', '大姐姐', '大熊', '1月16日', '呀呐');
INSERT INTO `animal` VALUES (803, '../images/小雅.png', '小雅', '♀', '普通', '食蚁兽', '2月6日', '优雅');
INSERT INTO `animal` VALUES (804, '../images/李彻.png', '李彻', '♂', '暴躁', '鸟', '1月27日', '贯彻');
INSERT INTO `animal` VALUES (805, '../images/熊大叔.png', '熊大叔', '♂', '自恋', '大熊', '9月27日', '咳咳');
INSERT INTO `animal` VALUES (806, '../images/朝阳.png', '朝阳', '♂', '暴躁', '大熊', '7月22日', '　');
INSERT INTO `animal` VALUES (807, '../images/凤尾.png', '凤尾', '♂', '悠闲', '鸟', '3月4日', '如斯');
INSERT INTO `animal` VALUES (808, '../images/穆穆.png', '穆穆', '♂', '暴躁', '大熊', '7月31日', '　');
INSERT INTO `animal` VALUES (809, '../images/安东尼.png', '安东尼', '♂', '自恋', '食蚁兽', '5月19日', '欧啦');
INSERT INTO `animal` VALUES (810, '../images/小酒窝.png', '小酒窝', '♀', '普通', '鸟', '3月12日', '脸红');
INSERT INTO `animal` VALUES (811, '../images/熊战士.png', '熊战士', '♂', '自恋', '大熊', '3月31日', 'over');
INSERT INTO `animal` VALUES (812, '../images/巴克思.png', '巴克思', '♂', '悠闲', '大熊', '8月16日', '嗯是');
INSERT INTO `animal` VALUES (813, '../images/佩希.png', '佩希', '♀', '元气', '食蚁兽', '11月9日', '希希');
INSERT INTO `animal` VALUES (814, '../images/叽叽.png', '叽叽', '♀', '元气', '鸟', '7月13日', '叽叽');
INSERT INTO `animal` VALUES (815, '../images/瑞秋.png', '瑞秋', '♀', '元气、大姐姐', '大熊', '3月22日', '耶呼');
INSERT INTO `animal` VALUES (816, '../images/太平.png', '太平', '♂', '运动', '大熊', '7月14日', '太好了');
INSERT INTO `animal` VALUES (817, '../images/余板.png', '余板', '♂', '悠闲', '鸟', '8月24日', '话说');
INSERT INTO `animal` VALUES (818, '../images/糖果.png', '糖果', '♀', '普通', '大熊', '3月13日', '舔舔');
INSERT INTO `animal` VALUES (819, '../images/爪爪.png', '爪爪', '♂', '暴躁', '大熊', '10月23日', '　');
INSERT INTO `animal` VALUES (820, '../images/有美.png', '有美', '♀', '元气', '食蚁兽', '2月16日', '真的假的');
INSERT INTO `animal` VALUES (821, '../images/纪诺.png', '纪诺', '♂', '运动', '鸟', '2月2日', '诺诺');
INSERT INTO `animal` VALUES (822, '../images/大功.png', '大功', '♂', '暴躁', '大熊', '5月16日', '施主');
INSERT INTO `animal` VALUES (823, '../images/丹丹.png', '丹丹', '♀', '元气', '大熊', '9月9日', '哇哦');
INSERT INTO `animal` VALUES (824, '../images/阿燕.png', '阿燕', '♂', '运动', '鸟', '7月17日', '呢喃');
INSERT INTO `animal` VALUES (825, '../images/恋恋.png', '恋恋', '♀', '元气', '大熊', '9月15日', '加油');
INSERT INTO `animal` VALUES (826, '../images/罗迪欧.png', '罗迪欧', '♂', '悠闲', '牛', '10月29日', '了不起');
INSERT INTO `animal` VALUES (827, '../images/柠檬娜.png', '柠檬娜', '♀', '普通', '猫', '3月27日', '娜个');
INSERT INTO `animal` VALUES (828, '../images/戈伍纪.png', '戈伍纪', '♂', '暴躁', '猫', '11月29日', '咦唷');
INSERT INTO `animal` VALUES (829, '../images/阿判.png', '阿判', '♂', '悠闲', '猫', '1月1日', '猫猫');
INSERT INTO `animal` VALUES (830, '../images/赵奇.png', '赵奇', '♂', '自恋', '鸟', '6月22日', '唷唷唷');
INSERT INTO `animal` VALUES (831, '../images/朱古莉.png', '朱古莉', '♀', '成熟', '猫', '2月15日', '古古');
INSERT INTO `animal` VALUES (832, '../images/纯纯.png', '纯纯', '♀', '元气', '猫', '6月17日', '蜜柑');
INSERT INTO `animal` VALUES (833, '../images/毛乐时.png', '毛乐时', '♂', '悠闲', '牛', '4月20日', '奔驰');
INSERT INTO `animal` VALUES (834, '../images/艳后.png', '艳后', '♀', '成熟', '猫', '9月22日', '尼罗');
INSERT INTO `animal` VALUES (835, '../images/阿一.png', '阿一', '♂', '运动', '猫', '8月1日', '喝');
INSERT INTO `animal` VALUES (836, '../images/圆圆.png', '圆圆', '♀', '普通', '猫', '9月25日', '喵');
INSERT INTO `animal` VALUES (837, '../images/文雄.png', '文雄', '♂', '运动', '鸟', '7月25日', '噗噗');
INSERT INTO `animal` VALUES (838, '../images/阿邦.png', '阿邦', '♂', '暴躁', '猫', '12月10日', '切');
INSERT INTO `animal` VALUES (839, '../images/尔光.png', '尔光', '♂', '悠闲', '猫', '4月11日', '晃晃');
INSERT INTO `animal` VALUES (840, '../images/罗宋.png', '罗宋', '♂', '悠闲、暴躁', '牛', '5月20日', '　');
INSERT INTO `animal` VALUES (841, '../images/珍珍.png', '珍珍', '♀', '成熟', '猫', '9月30日', '嗯哼');
INSERT INTO `animal` VALUES (842, '../images/彭花.png', '彭花', '♀', '元气', '猫', '2月27日', '看看');
INSERT INTO `animal` VALUES (843, '../images/周之翔.png', '周之翔', '♂', '运动', '鸟', '11月20日', '啁啁');
INSERT INTO `animal` VALUES (844, '../images/莎莎.png', '莎莎', '♀', '元气', '猫', '6月29日', '喵嗯');
INSERT INTO `animal` VALUES (845, '../images/小玉.png', '小玉', '♀', '成熟', '猫', '5月29日', '嗯嗯');
INSERT INTO `animal` VALUES (846, '../images/大常.png', '大常', '♂', '运动', '牛', '4月29日', '胡渣');
INSERT INTO `animal` VALUES (847, '../images/小虎.png', '小虎', '♀', '元气', '猫', '8月13日', '喵吼');
INSERT INTO `animal` VALUES (848, '../images/奥莉.png', '奥莉', '♀', '成熟', '猫', '2月3日', '什么');
INSERT INTO `animal` VALUES (849, '../images/施万德.png', '施万德', '♂', '暴躁', '牛', '4月30日', '　');
INSERT INTO `animal` VALUES (850, '../images/美佳.png', '美佳', '♀', '元气', '猫', '3月30日', '哪');
INSERT INTO `animal` VALUES (851, '../images/仁平.png', '仁平', '♂', '悠闲', '猫', '1月12日', '呐');
INSERT INTO `animal` VALUES (852, '../images/卢尔曼.png', '卢尔曼', '♂', '暴躁', '牛', '12月29日', '哞');
INSERT INTO `animal` VALUES (853, '../images/摔角鸦.png', '摔角鸦', '♂', '自恋', '鸟', '12月12日', '嘎');
INSERT INTO `animal` VALUES (854, '../images/男子汗.png', '男子汗', '♂', '运动', '猫', '8月17日', '打啊');
INSERT INTO `animal` VALUES (855, '../images/余子酱.png', '余子酱', '♀', '普通', '猫', '10月8日', '酱酱');
INSERT INTO `animal` VALUES (856, '../images/艾德豪.png', '艾德豪', '♂', '运动', '小熊', '9月28日', '精神');
INSERT INTO `animal` VALUES (857, '../images/沛希.png', '沛希', '♂', '悠闲', '鸡', '10月10日', '好棒');
INSERT INTO `animal` VALUES (858, '../images/樱桃.png', '樱桃', '♀', '元气', '小熊', '3月17日', '开玩笑的');
INSERT INTO `animal` VALUES (859, '../images/娃娃.png', '娃娃', '♀', '元气', '小熊', '6月24日', '怦怦');
INSERT INTO `animal` VALUES (860, '../images/金阁.png', '金阁', '♂', '暴躁', '鸡', '11月23日', '等待');
INSERT INTO `animal` VALUES (861, '../images/然姐.png', '然姐', '♀', '大姐姐', '小熊', '6月23日', '竟然说');
INSERT INTO `animal` VALUES (862, '../images/玩具熊.png', '玩具熊', '♂', '悠闲', '小熊', '2月10日', '玩玩');
INSERT INTO `animal` VALUES (863, '../images/黄金鸡.png', '黄金鸡', '♂', '悠闲', '鸡', '10月14日', '很优');
INSERT INTO `animal` VALUES (864, '../images/阿妹.png', '阿妹', '♀', '普通', '小熊', '5月21日', '有耶');
INSERT INTO `animal` VALUES (865, '../images/小枫.png', '小枫', '♀', '普通', '小熊', '6月15日', '熊仔');
INSERT INTO `animal` VALUES (866, '../images/凯西.png', '凯西', '♀', '成熟', '鸡', '10月24日', '咯咯');
INSERT INTO `animal` VALUES (867, '../images/玛丁.png', '玛丁', '♂', '悠闲', '小熊', '4月16日', '　');
INSERT INTO `animal` VALUES (868, '../images/嘉弼.png', '嘉弼', '♂', '暴躁', '小熊', '8月2日', '　');
INSERT INTO `animal` VALUES (869, '../images/茶茶.png', '茶茶', '♂', '运动', '猫', '12月20日', '之类的');
INSERT INTO `animal` VALUES (870, '../images/陶米咕.png', '陶米咕', '♀', '普通', '鸡', '4月28日', '是唷');
INSERT INTO `animal` VALUES (871, '../images/佳敏.png', '佳敏', '♀', '普通', '小熊', '5月18日', '佳佳');
INSERT INTO `animal` VALUES (872, '../images/蓬蓬.png', '蓬蓬', '♂', '运动', '小熊', '1月2日', '萌');
INSERT INTO `animal` VALUES (873, '../images/乌骨鸡.png', '乌骨鸡', '♂', '自恋', '鸡', '12月23日', '骨鸡');
INSERT INTO `animal` VALUES (874, '../images/美玲.png', '美玲', '♀', '成熟', '小熊', '3月10日', '哎呀');
INSERT INTO `animal` VALUES (875, '../images/宪雄.png', '宪雄', '♂', '暴躁', '小熊', '12月29日', '　');
INSERT INTO `animal` VALUES (876, '../images/巧巧.png', '巧巧', '♀', '大姐姐', '猫', '4月27日', '掰掰');
INSERT INTO `animal` VALUES (877, '../images/咏旋.png', '咏旋', '♀', '成熟', '鸡', '12月9日', '哈雷路亚');
INSERT INTO `animal` VALUES (878, '../images/胖达.png', '胖达', '♂', '悠闲', '小熊', '8月6日', '竹子');
INSERT INTO `animal` VALUES (879, '../images/阿钦.png', '阿钦', '♂', '悠闲', '小熊', '6月11日', '真是的');
INSERT INTO `animal` VALUES (880, '../images/阿排.png', '阿排', '♀', '元气', '奶牛', '5月10日', '牟');
INSERT INTO `animal` VALUES (881, '../images/肯肯.png', '肯肯', '♂', '运动', '鸡', '10月4日', '咕咕');
INSERT INTO `animal` VALUES (882, '../images/毕克萝.png', '毕克萝', '♀', '普通', '小熊', '7月12日', '马克杯');
INSERT INTO `animal` VALUES (883, '../images/杰克.png', '杰克', '♂', '自恋', '猫', '10月1日', '严肃');
INSERT INTO `animal` VALUES (884, '../images/帕塔雅.png', '帕塔雅', '♀', '元气、大姐姐', '鸡', '10月12日', '泰泰');
INSERT INTO `animal` VALUES (885, '../images/阿西.png', '阿西', '♂', '悠闲', '小熊', '3月2日', '算了');
INSERT INTO `animal` VALUES (886, '../images/阿龙.png', '阿龙', '♂', '悠闲', '鳄鱼', '2月12日', '然后');
INSERT INTO `animal` VALUES (887, '../images/牧牧.png', '牧牧', '♀', '成熟', '奶牛', '8月25日', '牛奶');
INSERT INTO `animal` VALUES (888, '../images/大吉.png', '大吉', '♂', '悠闲', '狗', '11月4日', '大概');
INSERT INTO `animal` VALUES (889, '../images/娣雅.png', '娣雅', '♀', '大姐姐', '鹿', '5月4日', '随便啦');
INSERT INTO `animal` VALUES (890, '../images/丰年.png', '丰年', '♂', '运动', '鳄鱼', '8月7日', '跳');
INSERT INTO `animal` VALUES (891, '../images/香草.png', '香草', '♀', '普通', '狗', '11月16日', '对不对');
INSERT INTO `animal` VALUES (892, '../images/查克.png', '查克', '♂', '悠闲', '鹿', '7月27日', '鹿鹿');
INSERT INTO `animal` VALUES (893, '../images/音音.png', '音音', '♀', '普通', '鹿', '3月26日', '小鹿');
INSERT INTO `animal` VALUES (894, '../images/晨曦.png', '晨曦', '♀', '普通', '奶牛', '9月20日', '微笑');
INSERT INTO `animal` VALUES (895, '../images/罗宾.png', '罗宾', '♂', '悠闲', '狗', '5月13日', '狗狗');
INSERT INTO `animal` VALUES (896, '../images/汤姆.png', '汤姆', '♂', '自恋', '鹿', '8月20日', '变了');
INSERT INTO `animal` VALUES (897, '../images/大和.png', '大和', '♂', '暴躁', '鳄鱼', '5月27日', '噗咻');
INSERT INTO `animal` VALUES (898, '../images/雀儿喜.png', '雀儿喜', '♀', '普通', '鹿', '1月18日', '　');
INSERT INTO `animal` VALUES (899, '../images/小健.png', '小健', '♂', '运动', '鹿', '11月7日', '梅花');
INSERT INTO `animal` VALUES (900, '../images/玉兰.png', '玉兰', '♀', '成熟', '奶牛', '2月28日', '　');
INSERT INTO `animal` VALUES (901, '../images/阿富.png', '阿富', '♂', '悠闲', '狗', '8月4日', '对吧');
INSERT INTO `animal` VALUES (902, '../images/洁西卡.png', '洁西卡', '♀', '大姐姐', '鹿', '9月19日', '西卡');
INSERT INTO `animal` VALUES (903, '../images/海德.png', '海德', '♂', '运动', '鳄鱼', '11月15日', '唰唰');
INSERT INTO `animal` VALUES (904, '../images/牛奶糖.png', '牛奶糖', '♀', '普通', '狗', '12月27日', '汪');
INSERT INTO `animal` VALUES (905, '../images/森森.png', '森森', '♂', '自恋', '鹿', '6月7日', '鹿营');
INSERT INTO `animal` VALUES (906, '../images/阿泥.png', '阿泥', '♂', '悠闲', '鳄鱼', '6月9日', '鳄泥');
INSERT INTO `animal` VALUES (907, '../images/傅兰.png', '傅兰', '♀', '成熟', '狗', '10月25日', '屋屋');
INSERT INTO `animal` VALUES (908, '../images/彼得.png', '彼得', '♂', '悠闲', '鹿', '4月5日', '怎么办');
INSERT INTO `animal` VALUES (909, '../images/爱莉.png', '爱莉', '♀', '普通', '鳄鱼', '5月17日', '鳄莉');
INSERT INTO `animal` VALUES (910, '../images/约翰.png', '约翰', '♂', '暴躁', '狗', '11月1日', '侬');
INSERT INTO `animal` VALUES (911, '../images/布鹿斯.png', '布鹿斯', '♂', '暴躁', '鹿', '5月26日', '福鹿寿');
INSERT INTO `animal` VALUES (912, '../images/鳄罗思.png', '鳄罗思', '♀', '成熟', '鳄鱼', '11月8日', '鳄鱼皮');
INSERT INTO `animal` VALUES (913, '../images/阿笨.png', '阿笨', '♂', '悠闲', '狗', '6月10日', '咆');
INSERT INTO `animal` VALUES (914, '../images/倪家莉.png', '倪家莉', '♀', '成熟', '鹿', '1月4日', '是吧');
INSERT INTO `animal` VALUES (915, '../images/球藻.png', '球藻', '♀', '普通', '鸭', '6月27日', '球球');
INSERT INTO `animal` VALUES (916, '../images/金牌.png', '金牌', '♂', '运动', '狗', '11月11日', '摘');
INSERT INTO `animal` VALUES (917, '../images/巨巨.png', '巨巨', '♂', '悠闲', '象', '7月14日', '象象');
INSERT INTO `animal` VALUES (918, '../images/肥肝.png', '肥肝', '♂', '悠闲', '鸭', '6月25日', '或许鸭');
INSERT INTO `animal` VALUES (919, '../images/皮蛋.png', '皮蛋', '♂', '运动', '鸭', '2月1日', '蛋是啊');
INSERT INTO `animal` VALUES (920, '../images/素返真.png', '素返真', '♀', '成熟', '鸭', '8月12日', '相反');
INSERT INTO `animal` VALUES (921, '../images/海苔裴.png', '海苔裴', '♀', '元气', '鸭', '2月11日', '裴裴');
INSERT INTO `animal` VALUES (922, '../images/文字烧.png', '文字烧', '♂', '悠闲', '狗', '12月31日', '什么字');
INSERT INTO `animal` VALUES (923, '../images/阿三.png', '阿三', '♂', '悠闲', '象', '10月3日', '哈啊');
INSERT INTO `animal` VALUES (924, '../images/阿守.png', '阿守', '♂', '运动', '鸭', '6月13日', '呱呱');
INSERT INTO `animal` VALUES (925, '../images/李察.png', '李察', '♂', '悠闲', '鸭', '1月3日', '鸭鸭');
INSERT INTO `animal` VALUES (926, '../images/珮琳.png', '珮琳', '♀', '元气', '狗', '6月18日', '琳琳');
INSERT INTO `animal` VALUES (927, '../images/亚美.png', '亚美', '♀', '普通', '鸭', '3月7日', '说不定鸭');
INSERT INTO `animal` VALUES (928, '../images/苏米.png', '苏米', '♀', '成熟', '鸭', '11月17日', '八十八');
INSERT INTO `animal` VALUES (929, '../images/小八.png', '小八', '♂', '悠闲', '狗', '8月3日', '那么那么');
INSERT INTO `animal` VALUES (930, '../images/艾勒芬.png', '艾勒芬', '♀', '成熟', '象', '12月8日', '鲁鲁');
INSERT INTO `animal` VALUES (931, '../images/卿德.png', '卿德', '♂', '悠闲', '鸭', '6月30日', '唧唧');
INSERT INTO `animal` VALUES (932, '../images/爱哭鬼.png', '爱哭鬼', '♀', '元气', '鸭', '2月23日', '呜呜');
INSERT INTO `animal` VALUES (933, '../images/麻蓉.png', '麻蓉', '♀', '元气', '狗', '1月11日', '一二');
INSERT INTO `animal` VALUES (934, '../images/何童.png', '何童', '♂', '自恋', '鸭', '12月22日', '说真的');
INSERT INTO `animal` VALUES (935, '../images/小鲔.png', '小鲔', '♀', '元气', '鸭', '2月19日', '鱼鱼');
INSERT INTO `animal` VALUES (936, '../images/花娜.png', '花娜', '♀', '大姐姐', '狗', '5月11日', '听说娜');
INSERT INTO `animal` VALUES (937, '../images/莎莉.png', '莎莉', '♀', '普通', '象', '1月28日', '莎啦啦');
INSERT INTO `animal` VALUES (938, '../images/米兰达.png', '米兰达', '♀', '成熟', '鸭', '4月23日', '怎么回事');
INSERT INTO `animal` VALUES (939, '../images/安妮.png', '安妮', '♀', '成熟', '鸭', '4月8日', '叹');
INSERT INTO `animal` VALUES (940, '../images/贝果.png', '贝果', '♀', '普通', '狗', '10月15日', '宾果');
INSERT INTO `animal` VALUES (941, '../images/露露.png', '露露', '♀', '成熟', '象', '1月20日', '勇');
INSERT INTO `animal` VALUES (942, '../images/阿坊.png', '阿坊', '♂', '悠闲', '鸭', '5月25日', '喂！妈妈');
INSERT INTO `animal` VALUES (943, '../images/包伯.png', '包伯', '♂', '自恋', '狗', '11月24日', '汪想想');
INSERT INTO `animal` VALUES (944, '../images/番茄酱.png', '番茄酱', '♀', '元气', '鸭', '7月27日', '噗吱');
INSERT INTO `animal` VALUES (945, '../images/阿刻.png', '阿刻', '♂', '悠闲', '青蛙', '7月8日', '嚼嚼');
INSERT INTO `animal` VALUES (946, '../images/啡卡.png', '啡卡', '♀', '元气', '象', '3月6日', '　');
INSERT INTO `animal` VALUES (947, '../images/比利.png', '比利', '♂', '暴躁', '山羊', '8月29日', '　');
INSERT INTO `animal` VALUES (948, '../images/翡翠.png', '翡翠', '♀', '普通', '青蛙', '10月27日', '是蛙');
INSERT INTO `animal` VALUES (949, '../images/迷仔.png', '迷仔', '♂', '暴躁', '青蛙', '6月5日', '喂');
INSERT INTO `animal` VALUES (950, '../images/大大.png', '大大', '♂', '运动', '象', '3月23日', '嘻嘻');
INSERT INTO `animal` VALUES (951, '../images/亨利.png', '亨利', '♂', '自恋', '青蛙', '9月21日', '滴咕');
INSERT INTO `animal` VALUES (952, '../images/阿田.png', '阿田', '♂', '运动', '青蛙', '8月3日', '蝌蚪');
INSERT INTO `animal` VALUES (953, '../images/庞克斯.png', '庞克斯', '♂', '暴躁', '象', '6月9日', '摇滚');
INSERT INTO `animal` VALUES (954, '../images/嘉俊.png', '嘉俊', '♂', '悠闲', '青蛙', '6月6日', '哈啾');
INSERT INTO `animal` VALUES (955, '../images/毒仔.png', '毒仔', '♂', '运动', '青蛙', '10月9日', '聒聒');
INSERT INTO `animal` VALUES (956, '../images/泡芙.png', '泡芙', '♀', '普通', '象', '5月12日', '啦啷');
INSERT INTO `animal` VALUES (957, '../images/雪儿.png', '雪儿', '♀', '普通', '山羊', '3月6日', '呗');
INSERT INTO `animal` VALUES (958, '../images/春卷.png', '春卷', '♂', '运动', '青蛙', '12月17日', '不客气');
INSERT INTO `animal` VALUES (959, '../images/雷妮.png', '雷妮', '♀', '普通', '青蛙', '2月4日', '雨雨');
INSERT INTO `animal` VALUES (960, '../images/林妲.png', '林妲', '♀', '成熟', '青蛙', '8月11日', '宝贝');
INSERT INTO `animal` VALUES (961, '../images/山姆.png', '山姆', '♂', '暴躁', '青蛙', '8月21日', '山山');
INSERT INTO `animal` VALUES (962, '../images/阿原.png', '阿原', '♂', '悠闲', '象', '9月7日', '毛毛');
INSERT INTO `animal` VALUES (963, '../images/墨墨.png', '墨墨', '♀', '普通', '山羊', '8月24日', '书');
INSERT INTO `animal` VALUES (964, '../images/吸管.png', '吸管', '♂', '悠闲、自恋', '青蛙', '7月9日', '喝喝');
INSERT INTO `animal` VALUES (965, '../images/锵锵.png', '锵锵', '♂', '运动', '青蛙', '2月13日', '机器');
INSERT INTO `animal` VALUES (966, '../images/太子.png', '太子', '♂', '暴躁', '青蛙', '7月18日', '子曰');
INSERT INTO `animal` VALUES (967, '../images/剪刀.png', '剪刀', '♀', '元气', '青蛙', '1月13日', '石头');
INSERT INTO `animal` VALUES (968, '../images/茉莉.png', '茉莉', '♀', '普通', '象', '11月18日', '呼');
INSERT INTO `animal` VALUES (969, '../images/亚星.png', '亚星', '♂', '运动', '山羊', '3月25日', '唷喏');
INSERT INTO `animal` VALUES (970, '../images/青呱.png', '青呱', '♂', '悠闲', '青蛙', '7月21日', '是的');
INSERT INTO `animal` VALUES (971, '../images/江适.png', '江适', '♂', '运动', '青蛙', '2月8日', '咕噜');
INSERT INTO `animal` VALUES (972, '../images/保罗.png', '保罗', '♂', '悠闲', '象', '5月5日', '保罗');
INSERT INTO `animal` VALUES (973, '../images/小睫.png', '小睫', '♀', '大姐姐', '青蛙', '10月2日', '蛤');
INSERT INTO `animal` VALUES (974, '../images/米米.png', '米米', '♂', '自恋', '仓鼠', '11月10日', '咻咻');
INSERT INTO `animal` VALUES (975, '../images/空空.png', '空空', '♂', '暴躁', '猩猩', '10月1日', '喔喔');
INSERT INTO `animal` VALUES (976, '../images/孔在来.png', '孔在来', '♂', '暴躁', '河马', '8月18日', '觉得是啦');
INSERT INTO `animal` VALUES (977, '../images/莉拉.png', '莉拉', '♀', '元气', '猩猩', '11月1日', '　');
INSERT INTO `animal` VALUES (978, '../images/阿朗.png', '阿朗', '♂', '暴躁', '猩猩', '9月6日', '拍胸脯');
INSERT INTO `animal` VALUES (979, '../images/欧世豪.png', '欧世豪', '♂', '运动、暴躁', '河马', '1月7日', '世世');
INSERT INTO `animal` VALUES (980, '../images/安安.png', '安安', '♀', '成熟', '仓鼠', '8月9日', '相信我');
INSERT INTO `animal` VALUES (981, '../images/吴紫眉.png', '吴紫眉', '♀', '元气、成熟', '猩猩', '9月1日', '唉呀');
INSERT INTO `animal` VALUES (982, '../images/班长.png', '班长', '♀', '成熟', '山羊', '1月14日', '起立');
INSERT INTO `animal` VALUES (983, '../images/曹珂.png', '曹珂', '♀', '元气', '河马', '9月18日', '是是');
INSERT INTO `animal` VALUES (984, '../images/哈姆.png', '哈姆', '♂', '运动', '仓鼠', '5月30日', '火腿');
INSERT INTO `animal` VALUES (985, '../images/哑铃.png', '哑铃', '♂', '暴躁', '猩猩', '9月11日', '高高');
INSERT INTO `animal` VALUES (986, '../images/戴维.png', '戴维', '♂', '自恋', '河马', '10月15日', 'Yes');
INSERT INTO `animal` VALUES (987, '../images/子墨.png', '子墨', '♂', '悠闲', '仓鼠', '10月19日', '忐忑不安');
INSERT INTO `animal` VALUES (988, '../images/阿保.png', '阿保', '♂', '悠闲', '猩猩', '10月18日', '呜呼');
INSERT INTO `animal` VALUES (989, '../images/文青.png', '文青', '♂', '悠闲、自恋', '山羊', '6月28日', '啊');
INSERT INTO `animal` VALUES (990, '../images/豆沙.png', '豆沙', '♀', '普通', '河马', '4月25日', '没错');
INSERT INTO `animal` VALUES (991, '../images/苹果.png', '苹果', '♀', '元气', '仓鼠', '9月24日', '转转');
INSERT INTO `animal` VALUES (992, '../images/万泰.png', '万泰', '♂', '运动', '猩猩', '9月12日', '这家伙');
INSERT INTO `animal` VALUES (993, '../images/威亚.png', '威亚', '♂', '运动', '马', '4月4日', '搞笑');
INSERT INTO `animal` VALUES (994, '../images/雪美.png', '雪美', '♀', '普通', '仓鼠', '1月30日', '对啊');
INSERT INTO `animal` VALUES (995, '../images/阿四.png', '阿四', '♀', '大姐姐', '猩猩', '4月14日', '煞啊');
INSERT INTO `animal` VALUES (996, '../images/芭芭拉.png', '芭芭拉', '♀', '大姐姐', '山羊', '12月26日', '或许芭');
INSERT INTO `animal` VALUES (997, '../images/贾宝为.png', '贾宝为', '♂', '运动', '河马', '3月29日', '因为');
INSERT INTO `animal` VALUES (998, '../images/麦麦.png', '麦麦', '♂', '自恋', '仓鼠', '6月20日', '就是这样');
INSERT INTO `animal` VALUES (999, '../images/壮壮.png', '壮壮', '♂', '运动', '猩猩', '3月26日', '钢钢');
INSERT INTO `animal` VALUES (1000, '../images/小仓.png', '小仓', '♂', '暴躁', '仓鼠', '2月25日', '怒');
INSERT INTO `animal` VALUES (1001, '../images/史奈鲁.png', '史奈鲁', '♂', '自恋', '猩猩', '12月5日', '同意');
INSERT INTO `animal` VALUES (1002, '../images/雷姆.png', '雷姆', '♂', '悠闲', '山羊', '1月18日', '轻飘');
INSERT INTO `animal` VALUES (1003, '../images/艾咪.png', '艾咪', '♀', '成熟', '河马', '10月6日', '哔哔');
INSERT INTO `animal` VALUES (1004, '../images/阿栗.png', '阿栗', '♂', '悠闲', '考拉', '5月7日', '颗颗');
INSERT INTO `animal` VALUES (1005, '../images/安索尼.png', '安索尼', '♂', '自恋', '马', '5月22日', '请看');
INSERT INTO `animal` VALUES (1006, '../images/草斑娜.png', '草斑娜', '♀', '普通', '马', '1月25日', '说到');
INSERT INTO `animal` VALUES (1007, '../images/亚莎.png', '亚莎', '♀', '成熟', '袋鼠', '11月12日', '嘿');
INSERT INTO `animal` VALUES (1008, '../images/莫儿.png', '莫儿', '♀', '普通', '考拉', '8月19日', '晶亮kira');
INSERT INTO `animal` VALUES (1009, '../images/小铀.png', '小铀', '♀', '成熟', '马', '2月9日', '游游');
INSERT INTO `animal` VALUES (1010, '../images/简培菈.png', '简培菈', '♀', '大姐姐', '考拉', '5月14日', '咦');
INSERT INTO `animal` VALUES (1011, '../images/小冈.png', '小冈', '♂', '悠闲', '马', '1月10日', '听说是');
INSERT INTO `animal` VALUES (1012, '../images/酥饼.png', '酥饼', '♂', '悠闲', '马', '10月5日', '酥酥');
INSERT INTO `animal` VALUES (1013, '../images/妈咪.png', '妈咪', '♀', '普通', '袋鼠', '12月5日', '亲亲');
INSERT INTO `animal` VALUES (1014, '../images/阿得.png', '阿得', '♀', '普通', '考拉', '4月12日', '不得了');
INSERT INTO `animal` VALUES (1015, '../images/小薰.png', '小薰', '♀', '普通', '马', '11月28日', '蹦');
INSERT INTO `animal` VALUES (1016, '../images/敖志明.png', '敖志明', '♂', '运动', '考拉', '10月12日', '哇。');
INSERT INTO `animal` VALUES (1017, '../images/朱黎.png', '朱黎', '♂', '自恋', '马', '3月15日', '喂！你');
INSERT INTO `animal` VALUES (1018, '../images/黑马.png', '黑马', '♂', '暴躁', '马', '6月16日', '布鲁鲁');
INSERT INTO `animal` VALUES (1019, '../images/童儿.png', '童儿', '♀', '成熟', '袋鼠', '9月8日', '庞克');
INSERT INTO `animal` VALUES (1020, '../images/思颖.png', '思颖', '♀', '普通', '考拉', '6月21日', '无尾熊。');
INSERT INTO `animal` VALUES (1021, '../images/舒芙蕾.png', '舒芙蕾', '♀', '成熟', '马', '12月2日', '　');
INSERT INTO `animal` VALUES (1022, '../images/罗奇.png', '罗奇', '♂', '自恋', '考拉', '10月26日', '喂喂');
INSERT INTO `animal` VALUES (1023, '../images/雷哈娜.png', '雷哈娜', '♀', '大姐姐', '马', '6月4日', '哼');
INSERT INTO `animal` VALUES (1024, '../images/马星星.png', '马星星', '♀', '元气', '马', '1月31日', '嘶嘶');
INSERT INTO `animal` VALUES (1025, '../images/希薇亚.png', '希薇亚', '♀', '成熟、大姐姐', '袋鼠', '5月3日', '对耶');
INSERT INTO `animal` VALUES (1026, '../images/钢锁.png', '钢锁', '♂', '暴躁', '考拉', '10月13日', '钱钱');
INSERT INTO `animal` VALUES (1027, '../images/笛笛.png', '笛笛', '♂', '悠闲', '马', '5月1日', '吹卷卷');
INSERT INTO `animal` VALUES (1028, '../images/圣萝.png', '圣萝', '♀', '元气', '马', '7月11日', '走哦');
INSERT INTO `animal` VALUES (1029, '../images/缝缝.png', '缝缝', '♀', '普通', '袋鼠', '10月11日', '补补');
INSERT INTO `animal` VALUES (1030, '../images/尤嘉莉.png', '尤嘉莉', '♀', '成熟', '考拉', '7月20日', '啊啦');
INSERT INTO `animal` VALUES (1031, '../images/马誉.png', '马誉', '♂', '自恋', '马', '9月16日', '　');
INSERT INTO `animal` VALUES (1032, '../images/袋钢.png', '袋钢', '♂', '暴躁', '袋鼠', '4月24日', '别装了');
INSERT INTO `animal` VALUES (1033, '../images/和平.png', '和平', '♂', '运动', '老鼠', '7月5日', '吱');
INSERT INTO `animal` VALUES (1034, '../images/皮猴.png', '皮猴', '♂', '暴躁', '猴子', '12月7日', '香蕉');
INSERT INTO `animal` VALUES (1035, '../images/皇狮.png', '皇狮', '♂', '暴躁', '狮子', '7月23日', '听懂吧');
INSERT INTO `animal` VALUES (1036, '../images/茜蓝.png', '茜蓝', '♂', '悠闲', '老鼠', '6月30日', '微微');
INSERT INTO `animal` VALUES (1037, '../images/杜美.png', '杜美', '♀', '普通', '老鼠', '2月18日', '美吧');
INSERT INTO `animal` VALUES (1038, '../images/赖恩睿.png', '赖恩睿', '♂', '自恋', '狮子', '7月29日', '正确');
INSERT INTO `animal` VALUES (1039, '../images/麦克.png', '麦克', '♂', '暴躁', '袋鼠', '12月1日', '做就对了');
INSERT INTO `animal` VALUES (1040, '../images/阿将.png', '阿将', '♂', '运动', '老鼠', '8月14日', '厉害');
INSERT INTO `animal` VALUES (1041, '../images/孟琪.png', '孟琪', '♀', '成熟', '猴子', '3月21日', '孟孟');
INSERT INTO `animal` VALUES (1042, '../images/晴天.png', '晴天', '♂', '悠闲', '狮子', '7月24日', '狮狮');
INSERT INTO `animal` VALUES (1043, '../images/阿聘.png', '阿聘', '♂', '运动', '老鼠', '9月13日', '可恶');
INSERT INTO `animal` VALUES (1044, '../images/韭菜.png', '韭菜', '♂', '暴躁', '老鼠', '10月17日', '非也');
INSERT INTO `animal` VALUES (1045, '../images/七七.png', '七七', '♀', '普通', '猴子', '8月23日', '唔唔');
INSERT INTO `animal` VALUES (1046, '../images/玛莉亚.png', '玛莉亚', '♀', '普通', '袋鼠', '5月31日', '好唷');
INSERT INTO `animal` VALUES (1047, '../images/甘油.png', '甘油', '♀', '元气', '老鼠', '4月13日', '滑滑');
INSERT INTO `animal` VALUES (1048, '../images/天佑.png', '天佑', '♂', '运动', '猴子', '11月21日', '差不多');
INSERT INTO `animal` VALUES (1049, '../images/老狮.png', '老狮', '♂', '运动、自恋', '狮子', '8月14日', '上课了');
INSERT INTO `animal` VALUES (1050, '../images/丸子.png', '丸子', '♀', '普通', '老鼠', '6月12日', '就说吧');
INSERT INTO `animal` VALUES (1051, '../images/贝拉.png', '贝拉', '♀', '元气', '老鼠', '12月28日', '嘎哈');
INSERT INTO `animal` VALUES (1052, '../images/远仁.png', '远仁', '♂', '悠闲', '猴子', '1月19日', '猿猿');
INSERT INTO `animal` VALUES (1053, '../images/悄俊.png', '悄俊', '♂', '暴躁', '老鼠', '1月17日', '叽叽');
INSERT INTO `animal` VALUES (1054, '../images/雪莉.png', '雪莉', '♀', '大姐姐', '猴子', '4月10日', '呜吱吱');
INSERT INTO `animal` VALUES (1055, '../images/李克.png', '李克', '♂', '运动', '狮子', '7月10日', '哈哈哈');
INSERT INTO `animal` VALUES (1056, '../images/西瓜皮.png', '西瓜皮', '♀', '成熟', '老鼠', '7月7日', '说说的');
INSERT INTO `animal` VALUES (1057, '../images/四月.png', '四月', '♀', '元气', '猴子', '4月2日', '哇呜');
INSERT INTO `animal` VALUES (1058, '../images/莫敬.png', '莫敬', '♂', '运动', '狮子', '8月8日', '男人');
INSERT INTO `animal` VALUES (1059, '../images/罗萱儿.png', '罗萱儿', '♀', '元气', '老鼠', '2月24日', '可爱');
INSERT INTO `animal` VALUES (1060, '../images/德里.png', '德里', '♂', '悠闲', '猴子', '5月24日', '去吧');
INSERT INTO `animal` VALUES (1061, '../images/亚瑟.png', '亚瑟', '♂', '运动', '狮子', '8月7日', '哪哈');
INSERT INTO `animal` VALUES (1062, '../images/蒂芬妮.png', '蒂芬妮', '♀', '普通', '老鹰', '3月25日', '是呢');
INSERT INTO `animal` VALUES (1063, '../images/火鸟.png', '火鸟', '♀', '大姐姐', '鸵鸟', '4月22日', '好热');
INSERT INTO `animal` VALUES (1064, '../images/果果.png', '果果', '♀', '成熟', '鸵鸟', '11月13日', '果然');
INSERT INTO `animal` VALUES (1065, '../images/安谷斯.png', '安谷斯', '♂', '暴躁', '老鹰', '2月22日', '溜溜');
INSERT INTO `animal` VALUES (1066, '../images/朱禄.png', '朱禄', '♂', '悠闲', '鸵鸟', '9月23日', '哎呀呀');
INSERT INTO `animal` VALUES (1067, '../images/起司.png', '起司', '♂', '自恋', '老鼠', '12月15日', '　');
INSERT INTO `animal` VALUES (1068, '../images/欧若拉.png', '欧若拉', '♀', '普通', '企鹅', '1月27日', '若');
INSERT INTO `animal` VALUES (1069, '../images/阿波罗.png', '阿波罗', '♂', '暴躁', '老鹰', '7月4日', '唔咿');
INSERT INTO `animal` VALUES (1070, '../images/仙仙.png', '仙仙', '♀', '普通', '鸵鸟', '1月15日', '千岁');
INSERT INTO `animal` VALUES (1071, '../images/浩克.png', '浩克', '♂', '暴躁', '老鹰', '7月30日', '多谢');
INSERT INTO `animal` VALUES (1072, '../images/凯恩.png', '凯恩', '♂', '自恋', '鸵鸟', '11月27日', '轰隆隆');
INSERT INTO `animal` VALUES (1073, '../images/张瑜.png', '张瑜', '♂', '暴躁', '章鱼', '9月20日', '章鱼');
INSERT INTO `animal` VALUES (1074, '../images/企鹅达.png', '企鹅达', '♂', '运动', '企鹅', '1月5日', '企鹅');
INSERT INTO `animal` VALUES (1075, '../images/安地斯.png', '安地斯', '♀', '成熟', '老鹰', '11月19日', '卡拉卡拉');
INSERT INTO `animal` VALUES (1076, '../images/小岚.png', '小岚', '♀', '普通', '鸵鸟', '10月21日', '鸵鸟');
INSERT INTO `animal` VALUES (1077, '../images/银阁.png', '银阁', '♂', '运动', '老鹰', '12月11日', '呀啊');
INSERT INTO `animal` VALUES (1078, '../images/小偲.png', '小偲', '♀', '成熟', '鸵鸟', '12月21日', '是嘛');
INSERT INTO `animal` VALUES (1079, '../images/章立娜.png', '章立娜', '♀', '普通', '章鱼', '6月26日', '咔');
INSERT INTO `animal` VALUES (1080, '../images/罗斯.png', '罗斯', '♂', '悠闲', '企鹅', '1月29日', '十字');
INSERT INTO `animal` VALUES (1081, '../images/谢博强.png', '谢博强', '♂', '运动', '老鹰', '1月8日', '啪沙啪沙');
INSERT INTO `animal` VALUES (1082, '../images/鹤兹.png', '鹤兹', '♂', '运动', '鸵鸟', '12月1日', '机械');
INSERT INTO `animal` VALUES (1083, '../images/如意.png', '如意', '♀', '成熟', '老鼠', '9月5日', '　');
INSERT INTO `animal` VALUES (1084, '../images/法兰克.png', '法兰克', '♂', '自恋', '老鹰', '6月1日', '是');
INSERT INTO `animal` VALUES (1085, '../images/胡拉拉.png', '胡拉拉', '♀', '元气', '鸵鸟', '2月9日', '红鹤');
INSERT INTO `animal` VALUES (1086, '../images/章丸丸.png', '章丸丸', '♂', '悠闲', '章鱼', '3月8日', '认同');
INSERT INTO `animal` VALUES (1087, '../images/达满.png', '达满', '♂', '暴躁', '企鹅', '4月6日', '“禅”');
INSERT INTO `animal` VALUES (1088, '../images/继光.png', '继光', '♂', '暴躁', '老鹰', '12月7日', '继继');
INSERT INTO `animal` VALUES (1089, '../images/朱莉亚.png', '朱莉亚', '♀', '成熟', '鸵鸟', '7月31日', '吼唷');
INSERT INTO `animal` VALUES (1090, '../images/小啾.png', '小啾', '♀', '元气', '老鼠', '2月5日', '啾啾');
INSERT INTO `animal` VALUES (1091, '../images/伊比利.png', '伊比利', '♂', '运动', '猪', '4月26日', '比利比利');
INSERT INTO `animal` VALUES (1092, '../images/胜利.png', '胜利', '♂', '运动', '猪', '7月26日', '感谢');
INSERT INTO `animal` VALUES (1093, '../images/谢宾娜.png', '谢宾娜', '♀', '成熟', '企鹅', '10月16日', '滑溜溜');
INSERT INTO `animal` VALUES (1094, '../images/仰韶.png', '仰韶', '♀', '普通', '兔子', '3月1日', '土俑');
INSERT INTO `animal` VALUES (1095, '../images/玛格.png', '玛格', '♀', '普通', '猪', '9月3日', '嗯');
INSERT INTO `animal` VALUES (1096, '../images/肉肉.png', '肉肉', '♂', '悠闲', '猪', '9月3日', '噗');
INSERT INTO `animal` VALUES (1097, '../images/花寿司.png', '花寿司', '♂', '运动', '企鹅', '11月2日', '卷卷');
INSERT INTO `animal` VALUES (1098, '../images/布兰妮.png', '布兰妮', '♀', '成熟', '猪', '11月14日', '讨厌啦~');
INSERT INTO `animal` VALUES (1099, '../images/嘟嘟.png', '嘟嘟', '♀', '元气', '猪', '7月28日', '哇塞');
INSERT INTO `animal` VALUES (1100, '../images/宝拉.png', '宝拉', '♀', '成熟', '企鹅', '1月23日', '唔呼呼');
INSERT INTO `animal` VALUES (1101, '../images/百川.png', '百川', '♂', '运动', '兔子', '11月3日', '忍忍');
INSERT INTO `animal` VALUES (1102, '../images/千惠.png', '千惠', '♀', '元气', '猪', '5月23日', '弹弹');
INSERT INTO `animal` VALUES (1103, '../images/博士.png', '博士', '♂', '运动', '猪', '10月7日', '公亩');
INSERT INTO `animal` VALUES (1104, '../images/伏特.png', '伏特', '♂', '自恋', '企鹅', '10月6日', '宝宝');
INSERT INTO `animal` VALUES (1105, '../images/古乃欣.png', '古乃欣', '♀', '大姐姐', '猪', '4月21日', '噗呼呼');
INSERT INTO `animal` VALUES (1106, '../images/古烈.png', '古烈', '♂', '暴躁', '猪', '4月7日', '万年');
INSERT INTO `animal` VALUES (1107, '../images/哈奇.png', '哈奇', '♂', '悠闲', '企鹅', '2月21日', '候补');
INSERT INTO `animal` VALUES (1108, '../images/小芽.png', '小芽', '♀', '普通', '猪', '3月5日', '当啷');
INSERT INTO `animal` VALUES (1109, '../images/达利.png', '达利', '♂', '暴躁', '猪', '11月6日', '噗嘻');
INSERT INTO `animal` VALUES (1110, '../images/蕾拉.png', '蕾拉', '♀', '大姐姐', '企鹅', '9月2日', '这样唷');
INSERT INTO `animal` VALUES (1111, '../images/莉莉安.png', '莉莉安', '♀', '元气', '兔子', '5月9日', '好像喔');
INSERT INTO `animal` VALUES (1112, '../images/阿猪.png', '阿猪', '♂', '悠闲', '猪', '12月30日', '懒懒');
INSERT INTO `animal` VALUES (1113, '../images/竹轮.png', '竹轮', '♂', '悠闲', '企鹅', '10月30日', '所以啦');
INSERT INTO `animal` VALUES (1114, '../images/豚皇.png', '豚皇', '♂', '自恋', '猪', '10月13日', '豚');
INSERT INTO `animal` VALUES (1115, '../images/冰莎.png', '冰莎', '♀', '元气', '企鹅', '2月20日', '凉爽');
INSERT INTO `animal` VALUES (1116, '../images/玛莎.png', '玛莎', '♀', '元气', '兔子', '3月14日', '啷');
INSERT INTO `animal` VALUES (1117, '../images/露西.png', '露西', '♀', '普通', '猪', '6月2日', '唷');
INSERT INTO `animal` VALUES (1118, '../images/秀益.png', '秀益', '♂', '悠闲', '企鹅', '2月7日', '轧轧');
INSERT INTO `animal` VALUES (1119, '../images/毛海儿.png', '毛海儿', '♀', '普通', '绵羊', '4月3日', '咩');
INSERT INTO `animal` VALUES (1120, '../images/咚比.png', '咚比', '♂', '自恋', '兔子', '7月10日', '　');
INSERT INTO `animal` VALUES (1121, '../images/阿醋.png', '阿醋', '♂', '悠闲', '兔子', '12月3日', '酸酸');
INSERT INTO `animal` VALUES (1122, '../images/草莓.png', '草莓', '♀', '普通', '犀牛', '3月19日', '糖糖');
INSERT INTO `animal` VALUES (1123, '../images/巧蔻.png', '巧蔻', '♀', '元气', '兔子', '1月6日', '真的');
INSERT INTO `animal` VALUES (1124, '../images/大姐头.png', '大姐头', '♀', '成熟', '兔子', '1月9日', '我说呀');
INSERT INTO `animal` VALUES (1125, '../images/毡毡.png', '毡毡', '♀', '普通', '绵羊', '4月9日', '羊毛');
INSERT INTO `animal` VALUES (1126, '../images/阿足.png', '阿足', '♂', '运动', '犀牛', '5月6日', '犀犀');
INSERT INTO `animal` VALUES (1127, '../images/法蓝琪.png', '法蓝琪', '♀', '成熟', '兔子', '1月22日', '噜啦啦');
INSERT INTO `animal` VALUES (1128, '../images/柴姐.png', '柴姐', '♀', '大姐姐', '犀牛', '5月28日', '超强');
INSERT INTO `animal` VALUES (1129, '../images/妙妙.png', '妙妙', '♀', '元气', '兔子', '3月3日', '不妙');
INSERT INTO `animal` VALUES (1130, '../images/儒林.png', '儒林', '♂', '运动', '兔子', '1月21日', '臣');
INSERT INTO `animal` VALUES (1131, '../images/梦梦.png', '梦梦', '♀', '普通', '犀牛', '1月24日', '嗯噗');
INSERT INTO `animal` VALUES (1132, '../images/克莉琪.png', '克莉琪', '♀', '元气', '兔子', '8月28日', '哩啦啦');
INSERT INTO `animal` VALUES (1133, '../images/猛兔.png', '猛兔', '♂', '暴躁', '兔子', '10月28日', '唔贺');
INSERT INTO `animal` VALUES (1134, '../images/绵绵.png', '绵绵', '♀', '普通', '绵羊', '4月16日', '就这样呀');
INSERT INTO `animal` VALUES (1135, '../images/阿甘.png', '阿甘', '♂', '悠闲', '兔子', '8月10日', '就是如此');
INSERT INTO `animal` VALUES (1136, '../images/月兔.png', '月兔', '♀', '元气', '兔子', '12月25日', '普通');
INSERT INTO `animal` VALUES (1137, '../images/阿蹲.png', '阿蹲', '♂', '暴躁', '犀牛', '6月17日', '混混');
INSERT INTO `animal` VALUES (1138, '../images/风杰.png', '风杰', '♂', '悠闲', '兔子', '3月11日', '风');
INSERT INTO `animal` VALUES (1139, '../images/珮琪.png', '珮琪', '♀', '元气', '兔子', '12月16日', '琪他');
INSERT INTO `animal` VALUES (1140, '../images/华尔滋.png', '华尔滋', '♀', '成熟', '绵羊', '3月28日', '　');
INSERT INTO `animal` VALUES (1141, '../images/蜜拉.png', '蜜拉', '♀', '大姐姐', '兔子', '7月6日', '月球');
INSERT INTO `animal` VALUES (1142, '../images/阿飞.png', '阿飞', '♂', '悠闲', '兔子', '3月16日', '是啦');
INSERT INTO `animal` VALUES (1143, '../images/光雄.png', '光雄', '♂', '悠闲', '犀牛', '3月20日', '念念');
INSERT INTO `animal` VALUES (1144, '../images/桑托斯.png', '桑托斯', '♂', '暴躁、自恋', '兔子', '7月24日', '朋友');
INSERT INTO `animal` VALUES (1145, '../images/罗塔.png', '罗塔', '♀', '元气', '兔子', '6月14日', '就这样啦');
INSERT INTO `animal` VALUES (1146, '../images/小芹.png', '小芹', '♀', '普通', '松鼠', '9月4日', '啦啦');
INSERT INTO `animal` VALUES (1147, '../images/瑞奇.png', '瑞奇', '♂', '悠闲', '松鼠', '6月3日', '是哦');
INSERT INTO `animal` VALUES (1148, '../images/雪花.png', '雪花', '♀', '元气', '绵羊', '8月15日', '一丝丝');
INSERT INTO `animal` VALUES (1149, '../images/小润.png', '小润', '♂', '自恋', '松鼠', '9月29日', '不管怎样');
INSERT INTO `animal` VALUES (1150, '../images/拉拉米.png', '拉拉米', '♀', '普通', '松鼠', '6月19日', '要是');
INSERT INTO `animal` VALUES (1151, '../images/彩星.png', '彩星', '♀', '普通', '绵羊', '12月25日', '　');
INSERT INTO `animal` VALUES (1152, '../images/娜塔丽.png', '娜塔丽', '♀', '成熟', '松鼠', '11月30日', '做得好');
INSERT INTO `animal` VALUES (1153, '../images/雷贝嘉.png', '雷贝嘉', '♀', '成熟', '松鼠', '9月10日', '正经');
INSERT INTO `animal` VALUES (1154, '../images/阿司.png', '阿司', '♀', '成熟', '绵羊', '10月21日', '　');
INSERT INTO `animal` VALUES (1155, '../images/闪电.png', '闪电', '♂', '暴躁', '松鼠', '7月9日', '闪闪');
INSERT INTO `animal` VALUES (1156, '../images/茶茶丸.png', '茶茶丸', '♂', '运动', '绵羊', '3月18日', '哇耶');
INSERT INTO `animal` VALUES (1157, '../images/爱睦.png', '爱睦', '♀', '成熟', '绵羊', '4月2日', '爱');
INSERT INTO `animal` VALUES (1158, '../images/孟珮.png', '孟珮', '♀', '普通', '松鼠', '10月22日', '咻');
INSERT INTO `animal` VALUES (1159, '../images/咬咬.png', '咬咬', '♀', '元气', '松鼠', '7月19日', '咯吱咯吱');
INSERT INTO `animal` VALUES (1160, '../images/温蒂.png', '温蒂', '♀', '大姐姐', '绵羊', '7月16日', '薯薯');
INSERT INTO `animal` VALUES (1161, '../images/小敏.png', '小敏', '♀', '成熟', '松鼠', '5月2日', '喔哼');
INSERT INTO `animal` VALUES (1162, '../images/小桃.png', '小桃', '♀', '元气', '松鼠', '6月8日', '就是唷');
INSERT INTO `animal` VALUES (1163, '../images/梅丽诺.png', '梅丽诺', '♀', '成熟', '绵羊', '11月26日', '　');
INSERT INTO `animal` VALUES (1164, '../images/软糖.png', '软糖', '♀', '普通', '松鼠', '8月5日', '甜甜');
INSERT INTO `animal` VALUES (1165, '../images/阿二.png', '阿二', '♀', '元气', '松鼠', '3月2日', '嘿唷');
INSERT INTO `animal` VALUES (1166, '../images/彭澎.png', '彭澎', '♀', '大姐姐', '绵羊', '2月14日', '辛苦了');
INSERT INTO `animal` VALUES (1167, '../images/嘉治.png', '嘉治', '♂', '暴躁', '松鼠', '9月14日', '炯炯');
INSERT INTO `animal` VALUES (1168, '../images/小影.png', '小影', '♀', '成熟', '松鼠', '7月3日', '哼哼');
INSERT INTO `animal` VALUES (1169, '../images/贾洛斯.png', '贾洛斯', '♂', '暴躁、自恋', '绵羊', '5月8日', '北鼻');
INSERT INTO `animal` VALUES (1170, '../images/克栗斯.png', '克栗斯', '♂', '运动', '松鼠', '2月26日', '鼓栗鼓栗');
INSERT INTO `animal` VALUES (1171, '../images/贾萝琳.png', '贾萝琳', '♀', '普通', '松鼠', '7月15日', '你');
INSERT INTO `animal` VALUES (1172, '../images/皮耶罗.png', '皮耶罗', '♂', '自恋', '绵羊', '4月19日', '丑丑');
INSERT INTO `animal` VALUES (1173, '../images/谷丰.png', '谷丰', '♂', '运动', '老虎', '8月19日', '虎虎');
INSERT INTO `animal` VALUES (1174, '../images/李可.png', '李可', '♂', '自恋', '狼', '12月6日', '喔耶');
INSERT INTO `animal` VALUES (1175, '../images/施傅.png', '施傅', '♂', '暴躁', '狼', '12月19日', '不是嘛');
INSERT INTO `animal` VALUES (1176, '../images/冰冰.png', '冰冰', '♀', '成熟', '狼', '12月14日', '就是说哇');
INSERT INTO `animal` VALUES (1177, '../images/卢姿.png', '卢姿', '♀', '元气', '老虎', '8月27日', '是喔');
INSERT INTO `animal` VALUES (1178, '../images/莫妮卡.png', '莫妮卡', '♀', '元气', '狼', '8月31日', '呀哈');
INSERT INTO `animal` VALUES (1179, '../images/潘奇隆.png', '潘奇隆', '♂', '暴躁', '狼', '11月5日', '不然呢');
INSERT INTO `animal` VALUES (1180, '../images/艾栗丝.png', '艾栗丝', '♀', '大姐姐', '松鼠', '8月30日', '当然哦');
INSERT INTO `animal` VALUES (1181, '../images/史培亚.png', '史培亚', '♂', '暴躁', '狼', '12月18日', '这倒是');
INSERT INTO `animal` VALUES (1182, '../images/阿彪.png', '阿彪', '♂', '运动', '老虎', '5月15日', '但是');
INSERT INTO `animal` VALUES (1183, '../images/罗博.png', '罗博', '♂', '暴躁', '狼', '11月25日', '罗罗');
INSERT INTO `animal` VALUES (1184, '../images/朱穆朗.png', '朱穆朗', '♂', '暴躁', '老虎', '8月22日', '王');
INSERT INTO `animal` VALUES (1185, '../images/范妮沙.png', '范妮沙', '♀', '成熟', '狼', '1月26日', '喔呵呵');
INSERT INTO `animal` VALUES (1186, '../images/马丽莲.png', '马丽莲', '♀', '成熟', '老虎', '11月22日', '啊哈');
INSERT INTO `animal` VALUES (1187, '../images/毕安卡.png', '毕安卡', '♀', '成熟', '狼', '9月17日', '漂亮');
INSERT INTO `animal` VALUES (1188, '../images/戈麦斯.png', '戈麦斯', '♂', '暴躁、运动', '老虎', '8月26日', '完全');
INSERT INTO `animal` VALUES (1189, '../images/百合.png', '百合', '♀', '普通', '狼', '3月24日', '花花');
INSERT INTO `animal` VALUES (1190, '../images/小雪.png', '小雪', '♀', '元气', '老虎', '12月13日', '雪豹');
INSERT INTO `animal` VALUES (1191, '../images/阿研.png', '阿研', '♂', '悠闲、暴躁', '狼', '2月17日', '咳呵');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
