/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50729
 Source Host           : 127.0.0.1:33060
 Source Schema         : dongsen

 Target Server Type    : MySQL
 Target Server Version : 50729
 File Encoding         : 65001

 Date: 08/05/2020 16:59:47
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for animal
-- ----------------------------
DROP TABLE IF EXISTS `animal`;
CREATE TABLE `animal` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `image` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `sex` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `character` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `race` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `birth` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `tag` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1589 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of animal
-- ----------------------------
BEGIN;
INSERT INTO `animal` VALUES (1192, '../images/animal/阳明.png', '阳明', '♂', '暴躁', '食蚁兽', '3月9日', '有的');
INSERT INTO `animal` VALUES (1193, '../images/animal/阿诚.png', '阿诚', '♂', '运动', '食蚁兽', '10月20日', '真诚');
INSERT INTO `animal` VALUES (1194, '../images/animal/贵妃.png', '贵妃', '♀', '成熟', '食蚁兽', '10月24日', '麻烦了');
INSERT INTO `animal` VALUES (1195, '../images/animal/丽婷.png', '丽婷', '♀', '元气', '鸟', '4月18日', '山雀');
INSERT INTO `animal` VALUES (1196, '../images/animal/恰咪.png', '恰咪', '♀', '元气、大姐姐', '大熊', '4月17日', '唷咻');
INSERT INTO `animal` VALUES (1197, '../images/animal/铁熊.png', '铁熊', '♂', '暴躁', '大熊', '7月1日', '嗯唔');
INSERT INTO `animal` VALUES (1198, '../images/animal/喳喳.png', '喳喳', '♀', '成熟', '鸟', '12月4日', '喳');
INSERT INTO `animal` VALUES (1199, '../images/animal/妮雅.png', '妮雅', '♀', '大姐姐', '大熊', '1月16日', '呀呐');
INSERT INTO `animal` VALUES (1200, '../images/animal/小雅.png', '小雅', '♀', '普通', '食蚁兽', '2月6日', '优雅');
INSERT INTO `animal` VALUES (1201, '../images/animal/李彻.png', '李彻', '♂', '暴躁', '鸟', '1月27日', '贯彻');
INSERT INTO `animal` VALUES (1202, '../images/animal/熊大叔.png', '熊大叔', '♂', '自恋', '大熊', '9月27日', '咳咳');
INSERT INTO `animal` VALUES (1203, '../images/animal/朝阳.png', '朝阳', '♂', '暴躁', '大熊', '7月22日', '　');
INSERT INTO `animal` VALUES (1204, '../images/animal/凤尾.png', '凤尾', '♂', '悠闲', '鸟', '3月4日', '如斯');
INSERT INTO `animal` VALUES (1205, '../images/animal/穆穆.png', '穆穆', '♂', '暴躁', '大熊', '7月31日', '　');
INSERT INTO `animal` VALUES (1206, '../images/animal/安东尼.png', '安东尼', '♂', '自恋', '食蚁兽', '5月19日', '欧啦');
INSERT INTO `animal` VALUES (1207, '../images/animal/小酒窝.png', '小酒窝', '♀', '普通', '鸟', '3月12日', '脸红');
INSERT INTO `animal` VALUES (1208, '../images/animal/熊战士.png', '熊战士', '♂', '自恋', '大熊', '3月31日', 'over');
INSERT INTO `animal` VALUES (1209, '../images/animal/巴克思.png', '巴克思', '♂', '悠闲', '大熊', '8月16日', '嗯是');
INSERT INTO `animal` VALUES (1210, '../images/animal/佩希.png', '佩希', '♀', '元气', '食蚁兽', '11月9日', '希希');
INSERT INTO `animal` VALUES (1211, '../images/animal/叽叽.png', '叽叽', '♀', '元气', '鸟', '7月13日', '叽叽');
INSERT INTO `animal` VALUES (1212, '../images/animal/瑞秋.png', '瑞秋', '♀', '元气、大姐姐', '大熊', '3月22日', '耶呼');
INSERT INTO `animal` VALUES (1213, '../images/animal/太平.png', '太平', '♂', '运动', '大熊', '7月14日', '太好了');
INSERT INTO `animal` VALUES (1214, '../images/animal/余板.png', '余板', '♂', '悠闲', '鸟', '8月24日', '话说');
INSERT INTO `animal` VALUES (1215, '../images/animal/糖果.png', '糖果', '♀', '普通', '大熊', '3月13日', '舔舔');
INSERT INTO `animal` VALUES (1216, '../images/animal/爪爪.png', '爪爪', '♂', '暴躁', '大熊', '10月23日', '　');
INSERT INTO `animal` VALUES (1217, '../images/animal/有美.png', '有美', '♀', '元气', '食蚁兽', '2月16日', '真的假的');
INSERT INTO `animal` VALUES (1218, '../images/animal/纪诺.png', '纪诺', '♂', '运动', '鸟', '2月2日', '诺诺');
INSERT INTO `animal` VALUES (1219, '../images/animal/大功.png', '大功', '♂', '暴躁', '大熊', '5月16日', '施主');
INSERT INTO `animal` VALUES (1220, '../images/animal/丹丹.png', '丹丹', '♀', '元气', '大熊', '9月9日', '哇哦');
INSERT INTO `animal` VALUES (1221, '../images/animal/阿燕.png', '阿燕', '♂', '运动', '鸟', '7月17日', '呢喃');
INSERT INTO `animal` VALUES (1222, '../images/animal/恋恋.png', '恋恋', '♀', '元气', '大熊', '9月15日', '加油');
INSERT INTO `animal` VALUES (1223, '../images/animal/罗迪欧.png', '罗迪欧', '♂', '悠闲', '牛', '10月29日', '了不起');
INSERT INTO `animal` VALUES (1224, '../images/animal/柠檬娜.png', '柠檬娜', '♀', '普通', '猫', '3月27日', '娜个');
INSERT INTO `animal` VALUES (1225, '../images/animal/戈伍纪.png', '戈伍纪', '♂', '暴躁', '猫', '11月29日', '咦唷');
INSERT INTO `animal` VALUES (1226, '../images/animal/阿判.png', '阿判', '♂', '悠闲', '猫', '1月1日', '猫猫');
INSERT INTO `animal` VALUES (1227, '../images/animal/赵奇.png', '赵奇', '♂', '自恋', '鸟', '6月22日', '唷唷唷');
INSERT INTO `animal` VALUES (1228, '../images/animal/朱古莉.png', '朱古莉', '♀', '成熟', '猫', '2月15日', '古古');
INSERT INTO `animal` VALUES (1229, '../images/animal/纯纯.png', '纯纯', '♀', '元气', '猫', '6月17日', '蜜柑');
INSERT INTO `animal` VALUES (1230, '../images/animal/毛乐时.png', '毛乐时', '♂', '悠闲', '牛', '4月20日', '奔驰');
INSERT INTO `animal` VALUES (1231, '../images/animal/艳后.png', '艳后', '♀', '成熟', '猫', '9月22日', '尼罗');
INSERT INTO `animal` VALUES (1232, '../images/animal/阿一.png', '阿一', '♂', '运动', '猫', '8月1日', '喝');
INSERT INTO `animal` VALUES (1233, '../images/animal/圆圆.png', '圆圆', '♀', '普通', '猫', '9月25日', '喵');
INSERT INTO `animal` VALUES (1234, '../images/animal/文雄.png', '文雄', '♂', '运动', '鸟', '7月25日', '噗噗');
INSERT INTO `animal` VALUES (1235, '../images/animal/阿邦.png', '阿邦', '♂', '暴躁', '猫', '12月10日', '切');
INSERT INTO `animal` VALUES (1236, '../images/animal/尔光.png', '尔光', '♂', '悠闲', '猫', '4月11日', '晃晃');
INSERT INTO `animal` VALUES (1237, '../images/animal/罗宋.png', '罗宋', '♂', '悠闲、暴躁', '牛', '5月20日', '　');
INSERT INTO `animal` VALUES (1238, '../images/animal/珍珍.png', '珍珍', '♀', '成熟', '猫', '9月30日', '嗯哼');
INSERT INTO `animal` VALUES (1239, '../images/animal/彭花.png', '彭花', '♀', '元气', '猫', '2月27日', '看看');
INSERT INTO `animal` VALUES (1240, '../images/animal/周之翔.png', '周之翔', '♂', '运动', '鸟', '11月20日', '啁啁');
INSERT INTO `animal` VALUES (1241, '../images/animal/莎莎.png', '莎莎', '♀', '元气', '猫', '6月29日', '喵嗯');
INSERT INTO `animal` VALUES (1242, '../images/animal/小玉.png', '小玉', '♀', '成熟', '猫', '5月29日', '嗯嗯');
INSERT INTO `animal` VALUES (1243, '../images/animal/大常.png', '大常', '♂', '运动', '牛', '4月29日', '胡渣');
INSERT INTO `animal` VALUES (1244, '../images/animal/小虎.png', '小虎', '♀', '元气', '猫', '8月13日', '喵吼');
INSERT INTO `animal` VALUES (1245, '../images/animal/奥莉.png', '奥莉', '♀', '成熟', '猫', '2月3日', '什么');
INSERT INTO `animal` VALUES (1246, '../images/animal/施万德.png', '施万德', '♂', '暴躁', '牛', '4月30日', '　');
INSERT INTO `animal` VALUES (1247, '../images/animal/美佳.png', '美佳', '♀', '元气', '猫', '3月30日', '哪');
INSERT INTO `animal` VALUES (1248, '../images/animal/仁平.png', '仁平', '♂', '悠闲', '猫', '1月12日', '呐');
INSERT INTO `animal` VALUES (1249, '../images/animal/卢尔曼.png', '卢尔曼', '♂', '暴躁', '牛', '12月29日', '哞');
INSERT INTO `animal` VALUES (1250, '../images/animal/摔角鸦.png', '摔角鸦', '♂', '自恋', '鸟', '12月12日', '嘎');
INSERT INTO `animal` VALUES (1251, '../images/animal/男子汗.png', '男子汗', '♂', '运动', '猫', '8月17日', '打啊');
INSERT INTO `animal` VALUES (1252, '../images/animal/余子酱.png', '余子酱', '♀', '普通', '猫', '10月8日', '酱酱');
INSERT INTO `animal` VALUES (1253, '../images/animal/艾德豪.png', '艾德豪', '♂', '运动', '小熊', '9月28日', '精神');
INSERT INTO `animal` VALUES (1254, '../images/animal/沛希.png', '沛希', '♂', '悠闲', '鸡', '10月10日', '好棒');
INSERT INTO `animal` VALUES (1255, '../images/animal/樱桃.png', '樱桃', '♀', '元气', '小熊', '3月17日', '开玩笑的');
INSERT INTO `animal` VALUES (1256, '../images/animal/娃娃.png', '娃娃', '♀', '元气', '小熊', '6月24日', '怦怦');
INSERT INTO `animal` VALUES (1257, '../images/animal/金阁.png', '金阁', '♂', '暴躁', '鸡', '11月23日', '等待');
INSERT INTO `animal` VALUES (1258, '../images/animal/然姐.png', '然姐', '♀', '大姐姐', '小熊', '6月23日', '竟然说');
INSERT INTO `animal` VALUES (1259, '../images/animal/玩具熊.png', '玩具熊', '♂', '悠闲', '小熊', '2月10日', '玩玩');
INSERT INTO `animal` VALUES (1260, '../images/animal/黄金鸡.png', '黄金鸡', '♂', '悠闲', '鸡', '10月14日', '很优');
INSERT INTO `animal` VALUES (1261, '../images/animal/阿妹.png', '阿妹', '♀', '普通', '小熊', '5月21日', '有耶');
INSERT INTO `animal` VALUES (1262, '../images/animal/小枫.png', '小枫', '♀', '普通', '小熊', '6月15日', '熊仔');
INSERT INTO `animal` VALUES (1263, '../images/animal/凯西.png', '凯西', '♀', '成熟', '鸡', '10月24日', '咯咯');
INSERT INTO `animal` VALUES (1264, '../images/animal/玛丁.png', '玛丁', '♂', '悠闲', '小熊', '4月16日', '　');
INSERT INTO `animal` VALUES (1265, '../images/animal/嘉弼.png', '嘉弼', '♂', '暴躁', '小熊', '8月2日', '　');
INSERT INTO `animal` VALUES (1266, '../images/animal/茶茶.png', '茶茶', '♂', '运动', '猫', '12月20日', '之类的');
INSERT INTO `animal` VALUES (1267, '../images/animal/陶米咕.png', '陶米咕', '♀', '普通', '鸡', '4月28日', '是唷');
INSERT INTO `animal` VALUES (1268, '../images/animal/佳敏.png', '佳敏', '♀', '普通', '小熊', '5月18日', '佳佳');
INSERT INTO `animal` VALUES (1269, '../images/animal/蓬蓬.png', '蓬蓬', '♂', '运动', '小熊', '1月2日', '萌');
INSERT INTO `animal` VALUES (1270, '../images/animal/乌骨鸡.png', '乌骨鸡', '♂', '自恋', '鸡', '12月23日', '骨鸡');
INSERT INTO `animal` VALUES (1271, '../images/animal/美玲.png', '美玲', '♀', '成熟', '小熊', '3月10日', '哎呀');
INSERT INTO `animal` VALUES (1272, '../images/animal/宪雄.png', '宪雄', '♂', '暴躁', '小熊', '12月29日', '　');
INSERT INTO `animal` VALUES (1273, '../images/animal/巧巧.png', '巧巧', '♀', '大姐姐', '猫', '4月27日', '掰掰');
INSERT INTO `animal` VALUES (1274, '../images/animal/咏旋.png', '咏旋', '♀', '成熟', '鸡', '12月9日', '哈雷路亚');
INSERT INTO `animal` VALUES (1275, '../images/animal/胖达.png', '胖达', '♂', '悠闲', '小熊', '8月6日', '竹子');
INSERT INTO `animal` VALUES (1276, '../images/animal/阿钦.png', '阿钦', '♂', '悠闲', '小熊', '6月11日', '真是的');
INSERT INTO `animal` VALUES (1277, '../images/animal/阿排.png', '阿排', '♀', '元气', '奶牛', '5月10日', '牟');
INSERT INTO `animal` VALUES (1278, '../images/animal/肯肯.png', '肯肯', '♂', '运动', '鸡', '10月4日', '咕咕');
INSERT INTO `animal` VALUES (1279, '../images/animal/毕克萝.png', '毕克萝', '♀', '普通', '小熊', '7月12日', '马克杯');
INSERT INTO `animal` VALUES (1280, '../images/animal/杰克.png', '杰克', '♂', '自恋', '猫', '10月1日', '严肃');
INSERT INTO `animal` VALUES (1281, '../images/animal/帕塔雅.png', '帕塔雅', '♀', '元气、大姐姐', '鸡', '10月12日', '泰泰');
INSERT INTO `animal` VALUES (1282, '../images/animal/阿西.png', '阿西', '♂', '悠闲', '小熊', '3月2日', '算了');
INSERT INTO `animal` VALUES (1283, '../images/animal/阿龙.png', '阿龙', '♂', '悠闲', '鳄鱼', '2月12日', '然后');
INSERT INTO `animal` VALUES (1284, '../images/animal/牧牧.png', '牧牧', '♀', '成熟', '奶牛', '8月25日', '牛奶');
INSERT INTO `animal` VALUES (1285, '../images/animal/大吉.png', '大吉', '♂', '悠闲', '狗', '11月4日', '大概');
INSERT INTO `animal` VALUES (1286, '../images/animal/娣雅.png', '娣雅', '♀', '大姐姐', '鹿', '5月4日', '随便啦');
INSERT INTO `animal` VALUES (1287, '../images/animal/丰年.png', '丰年', '♂', '运动', '鳄鱼', '8月7日', '跳');
INSERT INTO `animal` VALUES (1288, '../images/animal/香草.png', '香草', '♀', '普通', '狗', '11月16日', '对不对');
INSERT INTO `animal` VALUES (1289, '../images/animal/查克.png', '查克', '♂', '悠闲', '鹿', '7月27日', '鹿鹿');
INSERT INTO `animal` VALUES (1290, '../images/animal/音音.png', '音音', '♀', '普通', '鹿', '3月26日', '小鹿');
INSERT INTO `animal` VALUES (1291, '../images/animal/晨曦.png', '晨曦', '♀', '普通', '奶牛', '9月20日', '微笑');
INSERT INTO `animal` VALUES (1292, '../images/animal/罗宾.png', '罗宾', '♂', '悠闲', '狗', '5月13日', '狗狗');
INSERT INTO `animal` VALUES (1293, '../images/animal/汤姆.png', '汤姆', '♂', '自恋', '鹿', '8月20日', '变了');
INSERT INTO `animal` VALUES (1294, '../images/animal/大和.png', '大和', '♂', '暴躁', '鳄鱼', '5月27日', '噗咻');
INSERT INTO `animal` VALUES (1295, '../images/animal/雀儿喜.png', '雀儿喜', '♀', '普通', '鹿', '1月18日', '　');
INSERT INTO `animal` VALUES (1296, '../images/animal/小健.png', '小健', '♂', '运动', '鹿', '11月7日', '梅花');
INSERT INTO `animal` VALUES (1297, '../images/animal/玉兰.png', '玉兰', '♀', '成熟', '奶牛', '2月28日', '　');
INSERT INTO `animal` VALUES (1298, '../images/animal/阿富.png', '阿富', '♂', '悠闲', '狗', '8月4日', '对吧');
INSERT INTO `animal` VALUES (1299, '../images/animal/洁西卡.png', '洁西卡', '♀', '大姐姐', '鹿', '9月19日', '西卡');
INSERT INTO `animal` VALUES (1300, '../images/animal/海德.png', '海德', '♂', '运动', '鳄鱼', '11月15日', '唰唰');
INSERT INTO `animal` VALUES (1301, '../images/animal/牛奶糖.png', '牛奶糖', '♀', '普通', '狗', '12月27日', '汪');
INSERT INTO `animal` VALUES (1302, '../images/animal/森森.png', '森森', '♂', '自恋', '鹿', '6月7日', '鹿营');
INSERT INTO `animal` VALUES (1303, '../images/animal/阿泥.png', '阿泥', '♂', '悠闲', '鳄鱼', '6月9日', '鳄泥');
INSERT INTO `animal` VALUES (1304, '../images/animal/傅兰.png', '傅兰', '♀', '成熟', '狗', '10月25日', '屋屋');
INSERT INTO `animal` VALUES (1305, '../images/animal/彼得.png', '彼得', '♂', '悠闲', '鹿', '4月5日', '怎么办');
INSERT INTO `animal` VALUES (1306, '../images/animal/爱莉.png', '爱莉', '♀', '普通', '鳄鱼', '5月17日', '鳄莉');
INSERT INTO `animal` VALUES (1307, '../images/animal/约翰.png', '约翰', '♂', '暴躁', '狗', '11月1日', '侬');
INSERT INTO `animal` VALUES (1308, '../images/animal/布鹿斯.png', '布鹿斯', '♂', '暴躁', '鹿', '5月26日', '福鹿寿');
INSERT INTO `animal` VALUES (1309, '../images/animal/鳄罗思.png', '鳄罗思', '♀', '成熟', '鳄鱼', '11月8日', '鳄鱼皮');
INSERT INTO `animal` VALUES (1310, '../images/animal/阿笨.png', '阿笨', '♂', '悠闲', '狗', '6月10日', '咆');
INSERT INTO `animal` VALUES (1311, '../images/animal/倪家莉.png', '倪家莉', '♀', '成熟', '鹿', '1月4日', '是吧');
INSERT INTO `animal` VALUES (1312, '../images/animal/球藻.png', '球藻', '♀', '普通', '鸭', '6月27日', '球球');
INSERT INTO `animal` VALUES (1313, '../images/animal/金牌.png', '金牌', '♂', '运动', '狗', '11月11日', '摘');
INSERT INTO `animal` VALUES (1314, '../images/animal/巨巨.png', '巨巨', '♂', '悠闲', '象', '7月14日', '象象');
INSERT INTO `animal` VALUES (1315, '../images/animal/肥肝.png', '肥肝', '♂', '悠闲', '鸭', '6月25日', '或许鸭');
INSERT INTO `animal` VALUES (1316, '../images/animal/皮蛋.png', '皮蛋', '♂', '运动', '鸭', '2月1日', '蛋是啊');
INSERT INTO `animal` VALUES (1317, '../images/animal/素返真.png', '素返真', '♀', '成熟', '鸭', '8月12日', '相反');
INSERT INTO `animal` VALUES (1318, '../images/animal/海苔裴.png', '海苔裴', '♀', '元气', '鸭', '2月11日', '裴裴');
INSERT INTO `animal` VALUES (1319, '../images/animal/文字烧.png', '文字烧', '♂', '悠闲', '狗', '12月31日', '什么字');
INSERT INTO `animal` VALUES (1320, '../images/animal/阿三.png', '阿三', '♂', '悠闲', '象', '10月3日', '哈啊');
INSERT INTO `animal` VALUES (1321, '../images/animal/阿守.png', '阿守', '♂', '运动', '鸭', '6月13日', '呱呱');
INSERT INTO `animal` VALUES (1322, '../images/animal/李察.png', '李察', '♂', '悠闲', '鸭', '1月3日', '鸭鸭');
INSERT INTO `animal` VALUES (1323, '../images/animal/珮琳.png', '珮琳', '♀', '元气', '狗', '6月18日', '琳琳');
INSERT INTO `animal` VALUES (1324, '../images/animal/亚美.png', '亚美', '♀', '普通', '鸭', '3月7日', '说不定鸭');
INSERT INTO `animal` VALUES (1325, '../images/animal/苏米.png', '苏米', '♀', '成熟', '鸭', '11月17日', '八十八');
INSERT INTO `animal` VALUES (1326, '../images/animal/小八.png', '小八', '♂', '悠闲', '狗', '8月3日', '那么那么');
INSERT INTO `animal` VALUES (1327, '../images/animal/艾勒芬.png', '艾勒芬', '♀', '成熟', '象', '12月8日', '鲁鲁');
INSERT INTO `animal` VALUES (1328, '../images/animal/卿德.png', '卿德', '♂', '悠闲', '鸭', '6月30日', '唧唧');
INSERT INTO `animal` VALUES (1329, '../images/animal/爱哭鬼.png', '爱哭鬼', '♀', '元气', '鸭', '2月23日', '呜呜');
INSERT INTO `animal` VALUES (1330, '../images/animal/麻蓉.png', '麻蓉', '♀', '元气', '狗', '1月11日', '一二');
INSERT INTO `animal` VALUES (1331, '../images/animal/何童.png', '何童', '♂', '自恋', '鸭', '12月22日', '说真的');
INSERT INTO `animal` VALUES (1332, '../images/animal/小鲔.png', '小鲔', '♀', '元气', '鸭', '2月19日', '鱼鱼');
INSERT INTO `animal` VALUES (1333, '../images/animal/花娜.png', '花娜', '♀', '大姐姐', '狗', '5月11日', '听说娜');
INSERT INTO `animal` VALUES (1334, '../images/animal/莎莉.png', '莎莉', '♀', '普通', '象', '1月28日', '莎啦啦');
INSERT INTO `animal` VALUES (1335, '../images/animal/米兰达.png', '米兰达', '♀', '成熟', '鸭', '4月23日', '怎么回事');
INSERT INTO `animal` VALUES (1336, '../images/animal/安妮.png', '安妮', '♀', '成熟', '鸭', '4月8日', '叹');
INSERT INTO `animal` VALUES (1337, '../images/animal/贝果.png', '贝果', '♀', '普通', '狗', '10月15日', '宾果');
INSERT INTO `animal` VALUES (1338, '../images/animal/露露.png', '露露', '♀', '成熟', '象', '1月20日', '勇');
INSERT INTO `animal` VALUES (1339, '../images/animal/阿坊.png', '阿坊', '♂', '悠闲', '鸭', '5月25日', '喂！妈妈');
INSERT INTO `animal` VALUES (1340, '../images/animal/包伯.png', '包伯', '♂', '自恋', '狗', '11月24日', '汪想想');
INSERT INTO `animal` VALUES (1341, '../images/animal/番茄酱.png', '番茄酱', '♀', '元气', '鸭', '7月27日', '噗吱');
INSERT INTO `animal` VALUES (1342, '../images/animal/阿刻.png', '阿刻', '♂', '悠闲', '青蛙', '7月8日', '嚼嚼');
INSERT INTO `animal` VALUES (1343, '../images/animal/啡卡.png', '啡卡', '♀', '元气', '象', '3月6日', '　');
INSERT INTO `animal` VALUES (1344, '../images/animal/比利.png', '比利', '♂', '暴躁', '山羊', '8月29日', '　');
INSERT INTO `animal` VALUES (1345, '../images/animal/翡翠.png', '翡翠', '♀', '普通', '青蛙', '10月27日', '是蛙');
INSERT INTO `animal` VALUES (1346, '../images/animal/迷仔.png', '迷仔', '♂', '暴躁', '青蛙', '6月5日', '喂');
INSERT INTO `animal` VALUES (1347, '../images/animal/大大.png', '大大', '♂', '运动', '象', '3月23日', '嘻嘻');
INSERT INTO `animal` VALUES (1348, '../images/animal/亨利.png', '亨利', '♂', '自恋', '青蛙', '9月21日', '滴咕');
INSERT INTO `animal` VALUES (1349, '../images/animal/阿田.png', '阿田', '♂', '运动', '青蛙', '8月3日', '蝌蚪');
INSERT INTO `animal` VALUES (1350, '../images/animal/庞克斯.png', '庞克斯', '♂', '暴躁', '象', '6月9日', '摇滚');
INSERT INTO `animal` VALUES (1351, '../images/animal/嘉俊.png', '嘉俊', '♂', '悠闲', '青蛙', '6月6日', '哈啾');
INSERT INTO `animal` VALUES (1352, '../images/animal/毒仔.png', '毒仔', '♂', '运动', '青蛙', '10月9日', '聒聒');
INSERT INTO `animal` VALUES (1353, '../images/animal/泡芙.png', '泡芙', '♀', '普通', '象', '5月12日', '啦啷');
INSERT INTO `animal` VALUES (1354, '../images/animal/雪儿.png', '雪儿', '♀', '普通', '山羊', '3月6日', '呗');
INSERT INTO `animal` VALUES (1355, '../images/animal/春卷.png', '春卷', '♂', '运动', '青蛙', '12月17日', '不客气');
INSERT INTO `animal` VALUES (1356, '../images/animal/雷妮.png', '雷妮', '♀', '普通', '青蛙', '2月4日', '雨雨');
INSERT INTO `animal` VALUES (1357, '../images/animal/林妲.png', '林妲', '♀', '成熟', '青蛙', '8月11日', '宝贝');
INSERT INTO `animal` VALUES (1358, '../images/animal/山姆.png', '山姆', '♂', '暴躁', '青蛙', '8月21日', '山山');
INSERT INTO `animal` VALUES (1359, '../images/animal/阿原.png', '阿原', '♂', '悠闲', '象', '9月7日', '毛毛');
INSERT INTO `animal` VALUES (1360, '../images/animal/墨墨.png', '墨墨', '♀', '普通', '山羊', '8月24日', '书');
INSERT INTO `animal` VALUES (1361, '../images/animal/吸管.png', '吸管', '♂', '悠闲、自恋', '青蛙', '7月9日', '喝喝');
INSERT INTO `animal` VALUES (1362, '../images/animal/锵锵.png', '锵锵', '♂', '运动', '青蛙', '2月13日', '机器');
INSERT INTO `animal` VALUES (1363, '../images/animal/太子.png', '太子', '♂', '暴躁', '青蛙', '7月18日', '子曰');
INSERT INTO `animal` VALUES (1364, '../images/animal/剪刀.png', '剪刀', '♀', '元气', '青蛙', '1月13日', '石头');
INSERT INTO `animal` VALUES (1365, '../images/animal/茉莉.png', '茉莉', '♀', '普通', '象', '11月18日', '呼');
INSERT INTO `animal` VALUES (1366, '../images/animal/亚星.png', '亚星', '♂', '运动', '山羊', '3月25日', '唷喏');
INSERT INTO `animal` VALUES (1367, '../images/animal/青呱.png', '青呱', '♂', '悠闲', '青蛙', '7月21日', '是的');
INSERT INTO `animal` VALUES (1368, '../images/animal/江适.png', '江适', '♂', '运动', '青蛙', '2月8日', '咕噜');
INSERT INTO `animal` VALUES (1369, '../images/animal/保罗.png', '保罗', '♂', '悠闲', '象', '5月5日', '保罗');
INSERT INTO `animal` VALUES (1370, '../images/animal/小睫.png', '小睫', '♀', '大姐姐', '青蛙', '10月2日', '蛤');
INSERT INTO `animal` VALUES (1371, '../images/animal/米米.png', '米米', '♂', '自恋', '仓鼠', '11月10日', '咻咻');
INSERT INTO `animal` VALUES (1372, '../images/animal/空空.png', '空空', '♂', '暴躁', '猩猩', '10月1日', '喔喔');
INSERT INTO `animal` VALUES (1373, '../images/animal/孔在来.png', '孔在来', '♂', '暴躁', '河马', '8月18日', '觉得是啦');
INSERT INTO `animal` VALUES (1374, '../images/animal/莉拉.png', '莉拉', '♀', '元气', '猩猩', '11月1日', '　');
INSERT INTO `animal` VALUES (1375, '../images/animal/阿朗.png', '阿朗', '♂', '暴躁', '猩猩', '9月6日', '拍胸脯');
INSERT INTO `animal` VALUES (1376, '../images/animal/欧世豪.png', '欧世豪', '♂', '运动、暴躁', '河马', '1月7日', '世世');
INSERT INTO `animal` VALUES (1377, '../images/animal/安安.png', '安安', '♀', '成熟', '仓鼠', '8月9日', '相信我');
INSERT INTO `animal` VALUES (1378, '../images/animal/吴紫眉.png', '吴紫眉', '♀', '元气、成熟', '猩猩', '9月1日', '唉呀');
INSERT INTO `animal` VALUES (1379, '../images/animal/班长.png', '班长', '♀', '成熟', '山羊', '1月14日', '起立');
INSERT INTO `animal` VALUES (1380, '../images/animal/曹珂.png', '曹珂', '♀', '元气', '河马', '9月18日', '是是');
INSERT INTO `animal` VALUES (1381, '../images/animal/哈姆.png', '哈姆', '♂', '运动', '仓鼠', '5月30日', '火腿');
INSERT INTO `animal` VALUES (1382, '../images/animal/哑铃.png', '哑铃', '♂', '暴躁', '猩猩', '9月11日', '高高');
INSERT INTO `animal` VALUES (1383, '../images/animal/戴维.png', '戴维', '♂', '自恋', '河马', '10月15日', 'Yes');
INSERT INTO `animal` VALUES (1384, '../images/animal/子墨.png', '子墨', '♂', '悠闲', '仓鼠', '10月19日', '忐忑不安');
INSERT INTO `animal` VALUES (1385, '../images/animal/阿保.png', '阿保', '♂', '悠闲', '猩猩', '10月18日', '呜呼');
INSERT INTO `animal` VALUES (1386, '../images/animal/文青.png', '文青', '♂', '悠闲、自恋', '山羊', '6月28日', '啊');
INSERT INTO `animal` VALUES (1387, '../images/animal/豆沙.png', '豆沙', '♀', '普通', '河马', '4月25日', '没错');
INSERT INTO `animal` VALUES (1388, '../images/animal/苹果.png', '苹果', '♀', '元气', '仓鼠', '9月24日', '转转');
INSERT INTO `animal` VALUES (1389, '../images/animal/万泰.png', '万泰', '♂', '运动', '猩猩', '9月12日', '这家伙');
INSERT INTO `animal` VALUES (1390, '../images/animal/威亚.png', '威亚', '♂', '运动', '马', '4月4日', '搞笑');
INSERT INTO `animal` VALUES (1391, '../images/animal/雪美.png', '雪美', '♀', '普通', '仓鼠', '1月30日', '对啊');
INSERT INTO `animal` VALUES (1392, '../images/animal/阿四.png', '阿四', '♀', '大姐姐', '猩猩', '4月14日', '煞啊');
INSERT INTO `animal` VALUES (1393, '../images/animal/芭芭拉.png', '芭芭拉', '♀', '大姐姐', '山羊', '12月26日', '或许芭');
INSERT INTO `animal` VALUES (1394, '../images/animal/贾宝为.png', '贾宝为', '♂', '运动', '河马', '3月29日', '因为');
INSERT INTO `animal` VALUES (1395, '../images/animal/麦麦.png', '麦麦', '♂', '自恋', '仓鼠', '6月20日', '就是这样');
INSERT INTO `animal` VALUES (1396, '../images/animal/壮壮.png', '壮壮', '♂', '运动', '猩猩', '3月26日', '钢钢');
INSERT INTO `animal` VALUES (1397, '../images/animal/小仓.png', '小仓', '♂', '暴躁', '仓鼠', '2月25日', '怒');
INSERT INTO `animal` VALUES (1398, '../images/animal/史奈鲁.png', '史奈鲁', '♂', '自恋', '猩猩', '12月5日', '同意');
INSERT INTO `animal` VALUES (1399, '../images/animal/雷姆.png', '雷姆', '♂', '悠闲', '山羊', '1月18日', '轻飘');
INSERT INTO `animal` VALUES (1400, '../images/animal/艾咪.png', '艾咪', '♀', '成熟', '河马', '10月6日', '哔哔');
INSERT INTO `animal` VALUES (1401, '../images/animal/阿栗.png', '阿栗', '♂', '悠闲', '考拉', '5月7日', '颗颗');
INSERT INTO `animal` VALUES (1402, '../images/animal/安索尼.png', '安索尼', '♂', '自恋', '马', '5月22日', '请看');
INSERT INTO `animal` VALUES (1403, '../images/animal/草斑娜.png', '草斑娜', '♀', '普通', '马', '1月25日', '说到');
INSERT INTO `animal` VALUES (1404, '../images/animal/亚莎.png', '亚莎', '♀', '成熟', '袋鼠', '11月12日', '嘿');
INSERT INTO `animal` VALUES (1405, '../images/animal/莫儿.png', '莫儿', '♀', '普通', '考拉', '8月19日', '晶亮kira');
INSERT INTO `animal` VALUES (1406, '../images/animal/小铀.png', '小铀', '♀', '成熟', '马', '2月9日', '游游');
INSERT INTO `animal` VALUES (1407, '../images/animal/简培菈.png', '简培菈', '♀', '大姐姐', '考拉', '5月14日', '咦');
INSERT INTO `animal` VALUES (1408, '../images/animal/小冈.png', '小冈', '♂', '悠闲', '马', '1月10日', '听说是');
INSERT INTO `animal` VALUES (1409, '../images/animal/酥饼.png', '酥饼', '♂', '悠闲', '马', '10月5日', '酥酥');
INSERT INTO `animal` VALUES (1410, '../images/animal/妈咪.png', '妈咪', '♀', '普通', '袋鼠', '12月5日', '亲亲');
INSERT INTO `animal` VALUES (1411, '../images/animal/阿得.png', '阿得', '♀', '普通', '考拉', '4月12日', '不得了');
INSERT INTO `animal` VALUES (1412, '../images/animal/小薰.png', '小薰', '♀', '普通', '马', '11月28日', '蹦');
INSERT INTO `animal` VALUES (1413, '../images/animal/敖志明.png', '敖志明', '♂', '运动', '考拉', '10月12日', '哇。');
INSERT INTO `animal` VALUES (1414, '../images/animal/朱黎.png', '朱黎', '♂', '自恋', '马', '3月15日', '喂！你');
INSERT INTO `animal` VALUES (1415, '../images/animal/黑马.png', '黑马', '♂', '暴躁', '马', '6月16日', '布鲁鲁');
INSERT INTO `animal` VALUES (1416, '../images/animal/童儿.png', '童儿', '♀', '成熟', '袋鼠', '9月8日', '庞克');
INSERT INTO `animal` VALUES (1417, '../images/animal/思颖.png', '思颖', '♀', '普通', '考拉', '6月21日', '无尾熊。');
INSERT INTO `animal` VALUES (1418, '../images/animal/舒芙蕾.png', '舒芙蕾', '♀', '成熟', '马', '12月2日', '　');
INSERT INTO `animal` VALUES (1419, '../images/animal/罗奇.png', '罗奇', '♂', '自恋', '考拉', '10月26日', '喂喂');
INSERT INTO `animal` VALUES (1420, '../images/animal/雷哈娜.png', '雷哈娜', '♀', '大姐姐', '马', '6月4日', '哼');
INSERT INTO `animal` VALUES (1421, '../images/animal/马星星.png', '马星星', '♀', '元气', '马', '1月31日', '嘶嘶');
INSERT INTO `animal` VALUES (1422, '../images/animal/希薇亚.png', '希薇亚', '♀', '成熟、大姐姐', '袋鼠', '5月3日', '对耶');
INSERT INTO `animal` VALUES (1423, '../images/animal/钢锁.png', '钢锁', '♂', '暴躁', '考拉', '10月13日', '钱钱');
INSERT INTO `animal` VALUES (1424, '../images/animal/笛笛.png', '笛笛', '♂', '悠闲', '马', '5月1日', '吹卷卷');
INSERT INTO `animal` VALUES (1425, '../images/animal/圣萝.png', '圣萝', '♀', '元气', '马', '7月11日', '走哦');
INSERT INTO `animal` VALUES (1426, '../images/animal/缝缝.png', '缝缝', '♀', '普通', '袋鼠', '10月11日', '补补');
INSERT INTO `animal` VALUES (1427, '../images/animal/尤嘉莉.png', '尤嘉莉', '♀', '成熟', '考拉', '7月20日', '啊啦');
INSERT INTO `animal` VALUES (1428, '../images/animal/马誉.png', '马誉', '♂', '自恋', '马', '9月16日', '　');
INSERT INTO `animal` VALUES (1429, '../images/animal/袋钢.png', '袋钢', '♂', '暴躁', '袋鼠', '4月24日', '别装了');
INSERT INTO `animal` VALUES (1430, '../images/animal/和平.png', '和平', '♂', '运动', '老鼠', '7月5日', '吱');
INSERT INTO `animal` VALUES (1431, '../images/animal/皮猴.png', '皮猴', '♂', '暴躁', '猴子', '12月7日', '香蕉');
INSERT INTO `animal` VALUES (1432, '../images/animal/皇狮.png', '皇狮', '♂', '暴躁', '狮子', '7月23日', '听懂吧');
INSERT INTO `animal` VALUES (1433, '../images/animal/茜蓝.png', '茜蓝', '♂', '悠闲', '老鼠', '6月30日', '微微');
INSERT INTO `animal` VALUES (1434, '../images/animal/杜美.png', '杜美', '♀', '普通', '老鼠', '2月18日', '美吧');
INSERT INTO `animal` VALUES (1435, '../images/animal/赖恩睿.png', '赖恩睿', '♂', '自恋', '狮子', '7月29日', '正确');
INSERT INTO `animal` VALUES (1436, '../images/animal/麦克.png', '麦克', '♂', '暴躁', '袋鼠', '12月1日', '做就对了');
INSERT INTO `animal` VALUES (1437, '../images/animal/阿将.png', '阿将', '♂', '运动', '老鼠', '8月14日', '厉害');
INSERT INTO `animal` VALUES (1438, '../images/animal/孟琪.png', '孟琪', '♀', '成熟', '猴子', '3月21日', '孟孟');
INSERT INTO `animal` VALUES (1439, '../images/animal/晴天.png', '晴天', '♂', '悠闲', '狮子', '7月24日', '狮狮');
INSERT INTO `animal` VALUES (1440, '../images/animal/阿聘.png', '阿聘', '♂', '运动', '老鼠', '9月13日', '可恶');
INSERT INTO `animal` VALUES (1441, '../images/animal/韭菜.png', '韭菜', '♂', '暴躁', '老鼠', '10月17日', '非也');
INSERT INTO `animal` VALUES (1442, '../images/animal/七七.png', '七七', '♀', '普通', '猴子', '8月23日', '唔唔');
INSERT INTO `animal` VALUES (1443, '../images/animal/玛莉亚.png', '玛莉亚', '♀', '普通', '袋鼠', '5月31日', '好唷');
INSERT INTO `animal` VALUES (1444, '../images/animal/甘油.png', '甘油', '♀', '元气', '老鼠', '4月13日', '滑滑');
INSERT INTO `animal` VALUES (1445, '../images/animal/天佑.png', '天佑', '♂', '运动', '猴子', '11月21日', '差不多');
INSERT INTO `animal` VALUES (1446, '../images/animal/老狮.png', '老狮', '♂', '运动、自恋', '狮子', '8月14日', '上课了');
INSERT INTO `animal` VALUES (1447, '../images/animal/丸子.png', '丸子', '♀', '普通', '老鼠', '6月12日', '就说吧');
INSERT INTO `animal` VALUES (1448, '../images/animal/贝拉.png', '贝拉', '♀', '元气', '老鼠', '12月28日', '嘎哈');
INSERT INTO `animal` VALUES (1449, '../images/animal/远仁.png', '远仁', '♂', '悠闲', '猴子', '1月19日', '猿猿');
INSERT INTO `animal` VALUES (1450, '../images/animal/悄俊.png', '悄俊', '♂', '暴躁', '老鼠', '1月17日', '叽叽');
INSERT INTO `animal` VALUES (1451, '../images/animal/雪莉.png', '雪莉', '♀', '大姐姐', '猴子', '4月10日', '呜吱吱');
INSERT INTO `animal` VALUES (1452, '../images/animal/李克.png', '李克', '♂', '运动', '狮子', '7月10日', '哈哈哈');
INSERT INTO `animal` VALUES (1453, '../images/animal/西瓜皮.png', '西瓜皮', '♀', '成熟', '老鼠', '7月7日', '说说的');
INSERT INTO `animal` VALUES (1454, '../images/animal/四月.png', '四月', '♀', '元气', '猴子', '4月2日', '哇呜');
INSERT INTO `animal` VALUES (1455, '../images/animal/莫敬.png', '莫敬', '♂', '运动', '狮子', '8月8日', '男人');
INSERT INTO `animal` VALUES (1456, '../images/animal/罗萱儿.png', '罗萱儿', '♀', '元气', '老鼠', '2月24日', '可爱');
INSERT INTO `animal` VALUES (1457, '../images/animal/德里.png', '德里', '♂', '悠闲', '猴子', '5月24日', '去吧');
INSERT INTO `animal` VALUES (1458, '../images/animal/亚瑟.png', '亚瑟', '♂', '运动', '狮子', '8月7日', '哪哈');
INSERT INTO `animal` VALUES (1459, '../images/animal/蒂芬妮.png', '蒂芬妮', '♀', '普通', '老鹰', '3月25日', '是呢');
INSERT INTO `animal` VALUES (1460, '../images/animal/火鸟.png', '火鸟', '♀', '大姐姐', '鸵鸟', '4月22日', '好热');
INSERT INTO `animal` VALUES (1461, '../images/animal/果果.png', '果果', '♀', '成熟', '鸵鸟', '11月13日', '果然');
INSERT INTO `animal` VALUES (1462, '../images/animal/安谷斯.png', '安谷斯', '♂', '暴躁', '老鹰', '2月22日', '溜溜');
INSERT INTO `animal` VALUES (1463, '../images/animal/朱禄.png', '朱禄', '♂', '悠闲', '鸵鸟', '9月23日', '哎呀呀');
INSERT INTO `animal` VALUES (1464, '../images/animal/起司.png', '起司', '♂', '自恋', '老鼠', '12月15日', '　');
INSERT INTO `animal` VALUES (1465, '../images/animal/欧若拉.png', '欧若拉', '♀', '普通', '企鹅', '1月27日', '若');
INSERT INTO `animal` VALUES (1466, '../images/animal/阿波罗.png', '阿波罗', '♂', '暴躁', '老鹰', '7月4日', '唔咿');
INSERT INTO `animal` VALUES (1467, '../images/animal/仙仙.png', '仙仙', '♀', '普通', '鸵鸟', '1月15日', '千岁');
INSERT INTO `animal` VALUES (1468, '../images/animal/浩克.png', '浩克', '♂', '暴躁', '老鹰', '7月30日', '多谢');
INSERT INTO `animal` VALUES (1469, '../images/animal/凯恩.png', '凯恩', '♂', '自恋', '鸵鸟', '11月27日', '轰隆隆');
INSERT INTO `animal` VALUES (1470, '../images/animal/张瑜.png', '张瑜', '♂', '暴躁', '章鱼', '9月20日', '章鱼');
INSERT INTO `animal` VALUES (1471, '../images/animal/企鹅达.png', '企鹅达', '♂', '运动', '企鹅', '1月5日', '企鹅');
INSERT INTO `animal` VALUES (1472, '../images/animal/安地斯.png', '安地斯', '♀', '成熟', '老鹰', '11月19日', '卡拉卡拉');
INSERT INTO `animal` VALUES (1473, '../images/animal/小岚.png', '小岚', '♀', '普通', '鸵鸟', '10月21日', '鸵鸟');
INSERT INTO `animal` VALUES (1474, '../images/animal/银阁.png', '银阁', '♂', '运动', '老鹰', '12月11日', '呀啊');
INSERT INTO `animal` VALUES (1475, '../images/animal/小偲.png', '小偲', '♀', '成熟', '鸵鸟', '12月21日', '是嘛');
INSERT INTO `animal` VALUES (1476, '../images/animal/章立娜.png', '章立娜', '♀', '普通', '章鱼', '6月26日', '咔');
INSERT INTO `animal` VALUES (1477, '../images/animal/罗斯.png', '罗斯', '♂', '悠闲', '企鹅', '1月29日', '十字');
INSERT INTO `animal` VALUES (1478, '../images/animal/谢博强.png', '谢博强', '♂', '运动', '老鹰', '1月8日', '啪沙啪沙');
INSERT INTO `animal` VALUES (1479, '../images/animal/鹤兹.png', '鹤兹', '♂', '运动', '鸵鸟', '12月1日', '机械');
INSERT INTO `animal` VALUES (1480, '../images/animal/如意.png', '如意', '♀', '成熟', '老鼠', '9月5日', '　');
INSERT INTO `animal` VALUES (1481, '../images/animal/法兰克.png', '法兰克', '♂', '自恋', '老鹰', '6月1日', '是');
INSERT INTO `animal` VALUES (1482, '../images/animal/胡拉拉.png', '胡拉拉', '♀', '元气', '鸵鸟', '2月9日', '红鹤');
INSERT INTO `animal` VALUES (1483, '../images/animal/章丸丸.png', '章丸丸', '♂', '悠闲', '章鱼', '3月8日', '认同');
INSERT INTO `animal` VALUES (1484, '../images/animal/达满.png', '达满', '♂', '暴躁', '企鹅', '4月6日', '“禅”');
INSERT INTO `animal` VALUES (1485, '../images/animal/继光.png', '继光', '♂', '暴躁', '老鹰', '12月7日', '继继');
INSERT INTO `animal` VALUES (1486, '../images/animal/朱莉亚.png', '朱莉亚', '♀', '成熟', '鸵鸟', '7月31日', '吼唷');
INSERT INTO `animal` VALUES (1487, '../images/animal/小啾.png', '小啾', '♀', '元气', '老鼠', '2月5日', '啾啾');
INSERT INTO `animal` VALUES (1488, '../images/animal/伊比利.png', '伊比利', '♂', '运动', '猪', '4月26日', '比利比利');
INSERT INTO `animal` VALUES (1489, '../images/animal/胜利.png', '胜利', '♂', '运动', '猪', '7月26日', '感谢');
INSERT INTO `animal` VALUES (1490, '../images/animal/谢宾娜.png', '谢宾娜', '♀', '成熟', '企鹅', '10月16日', '滑溜溜');
INSERT INTO `animal` VALUES (1491, '../images/animal/仰韶.png', '仰韶', '♀', '普通', '兔子', '3月1日', '土俑');
INSERT INTO `animal` VALUES (1492, '../images/animal/玛格.png', '玛格', '♀', '普通', '猪', '9月3日', '嗯');
INSERT INTO `animal` VALUES (1493, '../images/animal/肉肉.png', '肉肉', '♂', '悠闲', '猪', '9月3日', '噗');
INSERT INTO `animal` VALUES (1494, '../images/animal/花寿司.png', '花寿司', '♂', '运动', '企鹅', '11月2日', '卷卷');
INSERT INTO `animal` VALUES (1495, '../images/animal/布兰妮.png', '布兰妮', '♀', '成熟', '猪', '11月14日', '讨厌啦~');
INSERT INTO `animal` VALUES (1496, '../images/animal/嘟嘟.png', '嘟嘟', '♀', '元气', '猪', '7月28日', '哇塞');
INSERT INTO `animal` VALUES (1497, '../images/animal/宝拉.png', '宝拉', '♀', '成熟', '企鹅', '1月23日', '唔呼呼');
INSERT INTO `animal` VALUES (1498, '../images/animal/百川.png', '百川', '♂', '运动', '兔子', '11月3日', '忍忍');
INSERT INTO `animal` VALUES (1499, '../images/animal/千惠.png', '千惠', '♀', '元气', '猪', '5月23日', '弹弹');
INSERT INTO `animal` VALUES (1500, '../images/animal/博士.png', '博士', '♂', '运动', '猪', '10月7日', '公亩');
INSERT INTO `animal` VALUES (1501, '../images/animal/伏特.png', '伏特', '♂', '自恋', '企鹅', '10月6日', '宝宝');
INSERT INTO `animal` VALUES (1502, '../images/animal/古乃欣.png', '古乃欣', '♀', '大姐姐', '猪', '4月21日', '噗呼呼');
INSERT INTO `animal` VALUES (1503, '../images/animal/古烈.png', '古烈', '♂', '暴躁', '猪', '4月7日', '万年');
INSERT INTO `animal` VALUES (1504, '../images/animal/哈奇.png', '哈奇', '♂', '悠闲', '企鹅', '2月21日', '候补');
INSERT INTO `animal` VALUES (1505, '../images/animal/小芽.png', '小芽', '♀', '普通', '猪', '3月5日', '当啷');
INSERT INTO `animal` VALUES (1506, '../images/animal/达利.png', '达利', '♂', '暴躁', '猪', '11月6日', '噗嘻');
INSERT INTO `animal` VALUES (1507, '../images/animal/蕾拉.png', '蕾拉', '♀', '大姐姐', '企鹅', '9月2日', '这样唷');
INSERT INTO `animal` VALUES (1508, '../images/animal/莉莉安.png', '莉莉安', '♀', '元气', '兔子', '5月9日', '好像喔');
INSERT INTO `animal` VALUES (1509, '../images/animal/阿猪.png', '阿猪', '♂', '悠闲', '猪', '12月30日', '懒懒');
INSERT INTO `animal` VALUES (1510, '../images/animal/竹轮.png', '竹轮', '♂', '悠闲', '企鹅', '10月30日', '所以啦');
INSERT INTO `animal` VALUES (1511, '../images/animal/豚皇.png', '豚皇', '♂', '自恋', '猪', '10月13日', '豚');
INSERT INTO `animal` VALUES (1512, '../images/animal/冰莎.png', '冰莎', '♀', '元气', '企鹅', '2月20日', '凉爽');
INSERT INTO `animal` VALUES (1513, '../images/animal/玛莎.png', '玛莎', '♀', '元气', '兔子', '3月14日', '啷');
INSERT INTO `animal` VALUES (1514, '../images/animal/露西.png', '露西', '♀', '普通', '猪', '6月2日', '唷');
INSERT INTO `animal` VALUES (1515, '../images/animal/秀益.png', '秀益', '♂', '悠闲', '企鹅', '2月7日', '轧轧');
INSERT INTO `animal` VALUES (1516, '../images/animal/毛海儿.png', '毛海儿', '♀', '普通', '绵羊', '4月3日', '咩');
INSERT INTO `animal` VALUES (1517, '../images/animal/咚比.png', '咚比', '♂', '自恋', '兔子', '7月10日', '　');
INSERT INTO `animal` VALUES (1518, '../images/animal/阿醋.png', '阿醋', '♂', '悠闲', '兔子', '12月3日', '酸酸');
INSERT INTO `animal` VALUES (1519, '../images/animal/草莓.png', '草莓', '♀', '普通', '犀牛', '3月19日', '糖糖');
INSERT INTO `animal` VALUES (1520, '../images/animal/巧蔻.png', '巧蔻', '♀', '元气', '兔子', '1月6日', '真的');
INSERT INTO `animal` VALUES (1521, '../images/animal/大姐头.png', '大姐头', '♀', '成熟', '兔子', '1月9日', '我说呀');
INSERT INTO `animal` VALUES (1522, '../images/animal/毡毡.png', '毡毡', '♀', '普通', '绵羊', '4月9日', '羊毛');
INSERT INTO `animal` VALUES (1523, '../images/animal/阿足.png', '阿足', '♂', '运动', '犀牛', '5月6日', '犀犀');
INSERT INTO `animal` VALUES (1524, '../images/animal/法蓝琪.png', '法蓝琪', '♀', '成熟', '兔子', '1月22日', '噜啦啦');
INSERT INTO `animal` VALUES (1525, '../images/animal/柴姐.png', '柴姐', '♀', '大姐姐', '犀牛', '5月28日', '超强');
INSERT INTO `animal` VALUES (1526, '../images/animal/妙妙.png', '妙妙', '♀', '元气', '兔子', '3月3日', '不妙');
INSERT INTO `animal` VALUES (1527, '../images/animal/儒林.png', '儒林', '♂', '运动', '兔子', '1月21日', '臣');
INSERT INTO `animal` VALUES (1528, '../images/animal/梦梦.png', '梦梦', '♀', '普通', '犀牛', '1月24日', '嗯噗');
INSERT INTO `animal` VALUES (1529, '../images/animal/克莉琪.png', '克莉琪', '♀', '元气', '兔子', '8月28日', '哩啦啦');
INSERT INTO `animal` VALUES (1530, '../images/animal/猛兔.png', '猛兔', '♂', '暴躁', '兔子', '10月28日', '唔贺');
INSERT INTO `animal` VALUES (1531, '../images/animal/绵绵.png', '绵绵', '♀', '普通', '绵羊', '4月16日', '就这样呀');
INSERT INTO `animal` VALUES (1532, '../images/animal/阿甘.png', '阿甘', '♂', '悠闲', '兔子', '8月10日', '就是如此');
INSERT INTO `animal` VALUES (1533, '../images/animal/月兔.png', '月兔', '♀', '元气', '兔子', '12月25日', '普通');
INSERT INTO `animal` VALUES (1534, '../images/animal/阿蹲.png', '阿蹲', '♂', '暴躁', '犀牛', '6月17日', '混混');
INSERT INTO `animal` VALUES (1535, '../images/animal/风杰.png', '风杰', '♂', '悠闲', '兔子', '3月11日', '风');
INSERT INTO `animal` VALUES (1536, '../images/animal/珮琪.png', '珮琪', '♀', '元气', '兔子', '12月16日', '琪他');
INSERT INTO `animal` VALUES (1537, '../images/animal/华尔滋.png', '华尔滋', '♀', '成熟', '绵羊', '3月28日', '　');
INSERT INTO `animal` VALUES (1538, '../images/animal/蜜拉.png', '蜜拉', '♀', '大姐姐', '兔子', '7月6日', '月球');
INSERT INTO `animal` VALUES (1539, '../images/animal/阿飞.png', '阿飞', '♂', '悠闲', '兔子', '3月16日', '是啦');
INSERT INTO `animal` VALUES (1540, '../images/animal/光雄.png', '光雄', '♂', '悠闲', '犀牛', '3月20日', '念念');
INSERT INTO `animal` VALUES (1541, '../images/animal/桑托斯.png', '桑托斯', '♂', '暴躁、自恋', '兔子', '7月24日', '朋友');
INSERT INTO `animal` VALUES (1542, '../images/animal/罗塔.png', '罗塔', '♀', '元气', '兔子', '6月14日', '就这样啦');
INSERT INTO `animal` VALUES (1543, '../images/animal/小芹.png', '小芹', '♀', '普通', '松鼠', '9月4日', '啦啦');
INSERT INTO `animal` VALUES (1544, '../images/animal/瑞奇.png', '瑞奇', '♂', '悠闲', '松鼠', '6月3日', '是哦');
INSERT INTO `animal` VALUES (1545, '../images/animal/雪花.png', '雪花', '♀', '元气', '绵羊', '8月15日', '一丝丝');
INSERT INTO `animal` VALUES (1546, '../images/animal/小润.png', '小润', '♂', '自恋', '松鼠', '9月29日', '不管怎样');
INSERT INTO `animal` VALUES (1547, '../images/animal/拉拉米.png', '拉拉米', '♀', '普通', '松鼠', '6月19日', '要是');
INSERT INTO `animal` VALUES (1548, '../images/animal/彩星.png', '彩星', '♀', '普通', '绵羊', '12月25日', '　');
INSERT INTO `animal` VALUES (1549, '../images/animal/娜塔丽.png', '娜塔丽', '♀', '成熟', '松鼠', '11月30日', '做得好');
INSERT INTO `animal` VALUES (1550, '../images/animal/雷贝嘉.png', '雷贝嘉', '♀', '成熟', '松鼠', '9月10日', '正经');
INSERT INTO `animal` VALUES (1551, '../images/animal/阿司.png', '阿司', '♀', '成熟', '绵羊', '10月21日', '　');
INSERT INTO `animal` VALUES (1552, '../images/animal/闪电.png', '闪电', '♂', '暴躁', '松鼠', '7月9日', '闪闪');
INSERT INTO `animal` VALUES (1553, '../images/animal/茶茶丸.png', '茶茶丸', '♂', '运动', '绵羊', '3月18日', '哇耶');
INSERT INTO `animal` VALUES (1554, '../images/animal/爱睦.png', '爱睦', '♀', '成熟', '绵羊', '4月2日', '爱');
INSERT INTO `animal` VALUES (1555, '../images/animal/孟珮.png', '孟珮', '♀', '普通', '松鼠', '10月22日', '咻');
INSERT INTO `animal` VALUES (1556, '../images/animal/咬咬.png', '咬咬', '♀', '元气', '松鼠', '7月19日', '咯吱咯吱');
INSERT INTO `animal` VALUES (1557, '../images/animal/温蒂.png', '温蒂', '♀', '大姐姐', '绵羊', '7月16日', '薯薯');
INSERT INTO `animal` VALUES (1558, '../images/animal/小敏.png', '小敏', '♀', '成熟', '松鼠', '5月2日', '喔哼');
INSERT INTO `animal` VALUES (1559, '../images/animal/小桃.png', '小桃', '♀', '元气', '松鼠', '6月8日', '就是唷');
INSERT INTO `animal` VALUES (1560, '../images/animal/梅丽诺.png', '梅丽诺', '♀', '成熟', '绵羊', '11月26日', '　');
INSERT INTO `animal` VALUES (1561, '../images/animal/软糖.png', '软糖', '♀', '普通', '松鼠', '8月5日', '甜甜');
INSERT INTO `animal` VALUES (1562, '../images/animal/阿二.png', '阿二', '♀', '元气', '松鼠', '3月2日', '嘿唷');
INSERT INTO `animal` VALUES (1563, '../images/animal/彭澎.png', '彭澎', '♀', '大姐姐', '绵羊', '2月14日', '辛苦了');
INSERT INTO `animal` VALUES (1564, '../images/animal/嘉治.png', '嘉治', '♂', '暴躁', '松鼠', '9月14日', '炯炯');
INSERT INTO `animal` VALUES (1565, '../images/animal/小影.png', '小影', '♀', '成熟', '松鼠', '7月3日', '哼哼');
INSERT INTO `animal` VALUES (1566, '../images/animal/贾洛斯.png', '贾洛斯', '♂', '暴躁、自恋', '绵羊', '5月8日', '北鼻');
INSERT INTO `animal` VALUES (1567, '../images/animal/克栗斯.png', '克栗斯', '♂', '运动', '松鼠', '2月26日', '鼓栗鼓栗');
INSERT INTO `animal` VALUES (1568, '../images/animal/贾萝琳.png', '贾萝琳', '♀', '普通', '松鼠', '7月15日', '你');
INSERT INTO `animal` VALUES (1569, '../images/animal/皮耶罗.png', '皮耶罗', '♂', '自恋', '绵羊', '4月19日', '丑丑');
INSERT INTO `animal` VALUES (1570, '../images/animal/谷丰.png', '谷丰', '♂', '运动', '老虎', '8月19日', '虎虎');
INSERT INTO `animal` VALUES (1571, '../images/animal/李可.png', '李可', '♂', '自恋', '狼', '12月6日', '喔耶');
INSERT INTO `animal` VALUES (1572, '../images/animal/施傅.png', '施傅', '♂', '暴躁', '狼', '12月19日', '不是嘛');
INSERT INTO `animal` VALUES (1573, '../images/animal/冰冰.png', '冰冰', '♀', '成熟', '狼', '12月14日', '就是说哇');
INSERT INTO `animal` VALUES (1574, '../images/animal/卢姿.png', '卢姿', '♀', '元气', '老虎', '8月27日', '是喔');
INSERT INTO `animal` VALUES (1575, '../images/animal/莫妮卡.png', '莫妮卡', '♀', '元气', '狼', '8月31日', '呀哈');
INSERT INTO `animal` VALUES (1576, '../images/animal/潘奇隆.png', '潘奇隆', '♂', '暴躁', '狼', '11月5日', '不然呢');
INSERT INTO `animal` VALUES (1577, '../images/animal/艾栗丝.png', '艾栗丝', '♀', '大姐姐', '松鼠', '8月30日', '当然哦');
INSERT INTO `animal` VALUES (1578, '../images/animal/史培亚.png', '史培亚', '♂', '暴躁', '狼', '12月18日', '这倒是');
INSERT INTO `animal` VALUES (1579, '../images/animal/阿彪.png', '阿彪', '♂', '运动', '老虎', '5月15日', '但是');
INSERT INTO `animal` VALUES (1580, '../images/animal/罗博.png', '罗博', '♂', '暴躁', '狼', '11月25日', '罗罗');
INSERT INTO `animal` VALUES (1581, '../images/animal/朱穆朗.png', '朱穆朗', '♂', '暴躁', '老虎', '8月22日', '王');
INSERT INTO `animal` VALUES (1582, '../images/animal/范妮沙.png', '范妮沙', '♀', '成熟', '狼', '1月26日', '喔呵呵');
INSERT INTO `animal` VALUES (1583, '../images/animal/马丽莲.png', '马丽莲', '♀', '成熟', '老虎', '11月22日', '啊哈');
INSERT INTO `animal` VALUES (1584, '../images/animal/毕安卡.png', '毕安卡', '♀', '成熟', '狼', '9月17日', '漂亮');
INSERT INTO `animal` VALUES (1585, '../images/animal/戈麦斯.png', '戈麦斯', '♂', '暴躁、运动', '老虎', '8月26日', '完全');
INSERT INTO `animal` VALUES (1586, '../images/animal/百合.png', '百合', '♀', '普通', '狼', '3月24日', '花花');
INSERT INTO `animal` VALUES (1587, '../images/animal/小雪.png', '小雪', '♀', '元气', '老虎', '12月13日', '雪豹');
INSERT INTO `animal` VALUES (1588, '../images/animal/阿研.png', '阿研', '♂', '悠闲、暴躁', '狼', '2月17日', '咳呵');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
